### ISSUE TITLE
Feature Request: Tooltip Scaling

### ISSUE THREAD

**Issue by ghost** [MisterPeModder/ShulkerBoxTooltip#102]
Hello, would it be possible to add individual tooltip scaling?
I would love to have that.
For me information about that look here please: https://github.com/Ivan-1F/tweakerplus/issues/5#issuecomment-1320941558
Greetings.

**Comment by MisterPeModder** [comment]
Interesting. I'm pretty sure the tooltips did scale when I implemented them a while back. I need to investigate this further, but does this problem occur when ShulkerBoxToltip is the only mod installed?

**Comment by ghost** [comment]
Hello @MisterPeModder,
SORRY for the late response. I have other mods installed as well.
I will check that today and in some time/hours I post my results.

**Comment by ghost** [comment]
Sorry again.
**I can confirm now, that it only happens if just Shulker Box Tooltip is installed.**
Easy Shulker Boxes and Packet Inventory are the two mods with their own overlay, I'm aware of from my pack.
I was disabling the Shulker/Ender overlay from them and used the one from Shulker Box Tooltip.

https://modrinth.com/mod/easy-shulker-boxes
https://modrinth.com/mod/packed-inventory

**Comment by MisterPeModder** [comment]
The bug happens with vanilla bundles as well, it is a problem with TweakerPlus not scaling the correct matrix that is used to render item stacks.
I am working with @Ivan-1F to fix this issue.

**Comment by ghost** [comment]
Awesome 😊
