### ISSUE TITLE
1.19.3 showing as 1.19.2 on CurseForge

### ISSUE THREAD

**Issue by Wolf-Syndrome** [MisterPeModder/ShulkerBoxTooltip#104]
On the curseforge page for ShulkerBoxTooltip you've released several 1.19.3 released but have labeled them under the 1.19.2. This causes an issue when users have installed 1.19.2 fabric mods and click update because it will auto-update to 1.19.3 version of fabric despite being on 1.19.2.

Errors such as 
Mixin apply for mod shulkerboxtooltip failed shulkerboxtooltip-common.mixins.json:client.ScreenMixin from mod shulkerboxtooltip
Will be thrown when someone has updated to 1.19.3 while on the 1.19.2 version

**Comment by ChristopherHaws** [comment]
Same with Modrinth

**Comment by MisterPeModder** [comment]
I fixed it when I saw your comments over on Curseforge yesterday, but thank you for reminding me anyway!
