### ISSUE TITLE
Suddenly stopped working?

### ISSUE THREAD

**Issue by XxSluggyzxX** [MisterPeModder/ShulkerBoxTooltip#109]
basically i have been using this mod for a few weeks and decided to downgrade from windows 11 to 10. I used it after downgrading and it worked fine but the next day the mod just wasnt working. i tried reinstalling the mod and tried reinstalling all the mods i had and all other mods worked fine except for shulkerbox tooltips. id love to get this working again as its pretty horrible playing without this mod now aha.

**Comment by XxSluggyzxX** [comment]
okay so i might have fixed it by actually installing the fabric version since im using fabric lmao

**Comment by MisterPeModder** [comment]
Yeah it is way too easy to download a version for the wrong mod loader on curseforge ^^
