### ISSUE TITLE
Crash - Fabric 1.19.3 - 3.0.9-beta.1+1.19-rc2

### ISSUE THREAD

**Issue by JeremyVyska** [MisterPeModder/ShulkerBoxTooltip#111]
#### Issue Description:

Crashing on startup

#### What happens:

Crash.

#### What you expected to happen:

Not crash  😄

#### Steps to reproduce:

1. just fired up a fresh Fabric 1.19.3 today
2. Added a variety of Fabric mods
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.9-beta.1+1.19-rc2
- Minecraft:  1.19.3 
- Fabric Loader: 0.14.14
- Fabric API: 0.73.2+1.19.3
- Other mods (if relevant): Listed in linked log

#### Your most recent log file where the issue was present: 

Relevant key bit:

```
[15:07:31] [Render thread/WARN]: Error loading class: net/minecraft/class_1159 (java.lang.ClassNotFoundException: net/minecraft/class_1159)
[15:07:31] [Render thread/ERROR]: Mixin apply for mod shulkerboxtooltip failed shulkerboxtooltip.client.json:ScreenMixin from mod shulkerboxtooltip -> net.minecraft.class_437: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> shulkerboxtooltip.client.json:ScreenMixin from mod shulkerboxtooltip -> Apply Methods -> (Lnet/minecraft/class_1159;Lnet/minecraft/class_287;IIIIIII)I:modify$bap000$updateTooltipLeftAndBottomPos -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> shulkerboxtooltip.client.json:ScreenMixin from mod shulkerboxtooltip -> Apply Methods -> (Lnet/minecraft/class_1159;Lnet/minecraft/class_287;IIIIIII)I:modify$bap000$updateTooltipLeftAndBottomPos -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
```

Full Log:  https://pastebin.com/LwhPPJ7Q

**Comment by JeremyVyska** [comment]
Just to play it safe, I stripped the installation down to only Fabric and SBT.  Still crashing, new pastebin:

https://pastebin.com/QXPFEhv2

**Comment by JeremyVyska** [comment]
You know what, you can close this up, but, the problem turns out to be:

On the Curse page, the Downloads section:
![image](https://user-images.githubusercontent.com/35526546/219871953-38676a00-820b-4119-9c12-409ef4ce8923.png)

It's still listing the Fabric most recent as the 3.0.9 RC.

Only once I dug into the longer Recent Files list did I find the [[Fabric 1.19.3] v3.2.4+1.19.3](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/files/4216174) version.

I'm guessing a variety of the "1.19.3 crashing" Curse comments are from this issue, so maybe there's a way to get the 3.2.4 version in the main download list for 1.19?

**Comment by MisterPeModder** [comment]
The way I understand it, Curseforge lists the latest release version along with the latest beta version, but doesn't distinguish between Forge and Fabric and I don't think there is a way to change this behavior like you can do with Modrinth.
I just added direct links to the latest version in the project page for the time being and see I if can update them automatically.
Thanks for reporting this issue though.
