### ISSUE TITLE
1.19.4 load error 

### ISSUE THREAD

**Issue by forditt** [MisterPeModder/ShulkerBoxTooltip#113]
The game won't load

- ShulkerBoxTooltip: [Fabric 1.19.3] v3.2.4+1.19.3
- Minecraft: 1.19.4
- Fabric Loader: 0.14.17
- Fabric API: 0.75.3

logs - https://pastebin.com/pm7Hbaqq

**Comment by MisterPeModder** [comment]
I will release a 1.19.4 soon.

**Comment by forditt** [comment]
thank you
