### ISSUE TITLE
Game crashes when used with Xaero's Beter PVP mod

### ISSUE THREAD

**Issue by JustSascha** [MisterPeModder/ShulkerBoxTooltip#114]
Better PVP has an option that shows a tooltip of the item you have in your hand for a few seconds, if you press shift while the tooltip is displayed, the game crashes with the error "java.lang.IllegalArgumentException: Unknown TooltipComponent".
I don't know if this issue can be fixed given that I assume it comes from both mods trying to access the same game file or something like that, but at least now you know.
I will also post an issue on Xaero's site to let him (her? they?) know as well.

#### Steps to reproduce:

1. Install both mods and make sure you activate the tooltip option in the Better PVP mod menu
2. Get a shulker box and put some items in it
3. Hold it in your hand and press shift (or whatever key you use to show the shulkerbox tooltip) while the Better PVP tooltip is still on screen (the Better PVP tooltip can be displayed for a longer time if you change the display time in the mod menu)
4. Your game should now have crashed

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.2.4
- Minecraft: 1.19.3
- Fabric Loader: 0.14.17
- Fabric API: 0.75.1
- Other mods: Better PVP 23.3.1

[Crash_Report.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/11008978/Crash_Report.txt)

**Comment by MisterPeModder** [comment]
Hi, I can reproduce the issue locally, however it seems Xaero's Better PVP is the cause. I sent a message to Xaero over at [the Minecraft forums](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2195449-better-pvp-mod-1-19-4-forge-fabric-1-18-2-1-17-1-1?comment=828).

**Comment by JustSascha** [comment]
Cool! I figured the source of the bug would be xaero's given that only his mod's logs are shown on the crash report, but I'd rather let everyone involved know of the issue just in case. Thanks for the reply, though!

**Comment by JustSascha** [comment]
Update on this, the bug is fixed! With the new 23.3.2 version of the BetterPvP mod the issue is completely fixed and the shulkerbox tooltip shows the inventory of the shulker box even in the BetterPvP tooltip.
