### ISSUE TITLE
Ender chest preview doesn't work on realms

### ISSUE THREAD

**Issue by CarlCarlovich** [MisterPeModder/ShulkerBoxTooltip#115]
#### Issue Description:

Hovering an ender chest doesn't display a preview. I have all settings enabled, tried both passive and active. Have tried opening and closing in all dimensions and nothing pops up.

#### What you expected to happen: See ender chest contents

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.2.5
- Minecraft: 1.19.4
- Fabric Loader: 0.11.2
- Fabric API: 0.77.0
- Other mods (if relevant):

**Comment by MisterPeModder** [comment]
Hello, ender chest previews require the mod to be installed server-side.
As mods cannot be installed on Realms the feature will not work there.
