### ISSUE TITLE
I wanna know what enchantments are in an item without opening

### ISSUE THREAD

**Issue by ItzYotam** [MisterPeModder/ShulkerBoxTooltip#116]
it will help me a lot if someone knows how to do that.

I am on a server that most of the people there love to scam
so when I have shulker tooltip I cant see enchantments so like armor that is "Prot V" is going to be prot I
so yeah if anyone knows how to do that please tell me, thanks

**Comment by ItzYotam** [comment]
if I need to config it in a coding program I have no problem just tell me the line of code to type and where to put it

**Comment by ItzYotamGaming** [comment]
I found out how to do that so ty anyway!

**Comment by ItzYotam** [comment]
so did anyone see this?

**Comment by ItzYotam** [comment]
hellloooooooooooo

**Comment by MisterPeModder** [comment]
Hello, you cannot currently the tooltip of items within previews, this is a requested feature (issue #48).
I plan to work on it, but I will focus on releasing the mod for Minecraft 1.20 first.
