### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by imTyyde** [MisterPeModder/ShulkerBoxTooltip#118]
I've downloaded ModMenu so that I can access the options for this mod and selected ShulkerBoxTooltip, but there is no button to access the options unlike other mods.
![2](https://user-images.githubusercontent.com/132800786/236657382-0b49e03b-b0e8-4c55-9122-c763d118d26c.png)
![1](https://user-images.githubusercontent.com/132800786/236657384-8eee0684-d73d-4a2d-92be-64470ea96809.png)

**Comment by MisterPeModder** [comment]
Hello, are you using the latest version of the mod ?

**Comment by soapsito** [comment]
si la 1.19.2

**Comment by soapsito** [comment]
> Hola, ¿estás usando la última versión del mod?

si la 1.19.2
