### ISSUE TITLE
is there anyway to turn off the compact mode entirely?

### ISSUE THREAD

**Issue by pleepish** [MisterPeModder/ShulkerBoxTooltip#119]
i would really like to be able to see my entire shulker inventory without the compact mode.

**Comment by zenenwjaimes** [comment]
There's a combination of using `swapModes` that if you set to true will do what you want. I don't have modmenu installed on my setup at the moment so I can't give you the exact settings needed but you can definitely get the full preview mode to always show by default.

**Comment by zenenwjaimes** [comment]
If you do the `swapModes` suggestion I made and always have the `preview` set to `true`, you'll always have the full preview available no matter what. I had made a mod that did this exact same thing but found this even better implementation. I hope this helps you and I can't wait for this mod to update to `1.20`.

**Comment by MisterPeModder** [comment]
As @zenenwjaimes said, you can enable `swapModes` to always show the full preview by default. If you want to never see the compact mode even when pressing the full preview key, you can unbind it (by pressing escape) in the `Controls` category of the configuration menu.
