### ISSUE TITLE
Suggestion: Add one decimal place to boxes with over 1k items

### ISSUE THREAD

**Issue by QarthO** [MisterPeModder/ShulkerBoxTooltip#121]
Currently: 
![image](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/10179096/ae18e2c9-8843-4dd4-80ee-a750bab6dc13)
A full shulker box has 1728 items in it. However the tooltip only shows 1k. Which is no where near accurate

It would make a lot of sense to have the tooltip show 1.7k

**Comment by MisterPeModder** [comment]
![image](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/7838479/57f9e6be-2fbc-4570-ae58-38747a4c5385)

Fixed! This will be available in the next releases for 1.19 and 1.20.
