### ISSUE TITLE
Ctrl + Q not working inside inventory when ShulkerBoxTooltip is installed

### ISSUE THREAD

**Issue by Jessuhh** [MisterPeModder/ShulkerBoxTooltip#123]
#### Issue Description:

`Ctrl + Q` not working inside inventory when ShulkerBoxTooltip is installed.

#### What happens:

When you hover over an item in your or any inventory and press `Ctrl + Q` to drop the whole stack nothing drops. Pressing `Ctrl + Q` while ingame (**not** in an inventory) works as intended.

To solve this issue go to the ShulkerBoxTooltip settings > Controls > Lock tooltip and rebind or unbind this control.

#### What you expected to happen:

A stack of items to drop.

#### Steps to reproduce:

1. Open any inventory
2. Hold `Ctrl`
3. Press `Q` once
4. Nothing drops (the stack of items should drop)

____
#### Affected Versions:

- ShulkerBoxTooltip: v4.0.1+1.20
- Minecraft: 1.20
- Fabric Loader: 0.14.21-1.20
- Fabric API: 0.83.0+1.20
- Other mods (if relevant): Tested with only fabric api and the ShulkerBoxTooltip mod, issue still occurs

#### Your most recent log file where the issue was present: 

https://paste.klaasboer.org/obJWxL

**Comment by MisterPeModder** [comment]
HI, it turns out than *no* shortcut works at all while holding control and hovering an item (e.g. moving items with number keys).
Funnily enough, they work when previewing containers though.
I will look into patching this ASAP.
