### ISSUE TITLE
Crash on Linux Mint

### ISSUE THREAD

**Issue by greggh** [MisterPeModder/ShulkerBoxTooltip#125]
#### Issue Description:

Adding this mod to my mods folder on Linux Mint causes Minecraft not to load. It returns to the launcher with exit code 1.

#### What happens:

Minecraft crashes

#### What you expected to happen:

Not crashing.

#### Steps to reproduce:

1. Install Minecraft in Linux Mint.
2. Add mods folder.
3. Put ShulkerBoxTooltip into mods folder.
4. Launch Minecraft.
5. Crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-fabric-3.4.0+1.19.4
- Minecraft: 1.20.1
- Fabric Loader: 0.14.21
- Fabric API: fabric-api-0.84.0+1.20.1
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/11823985/latest.log)
[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
It seems you are running the 1.19.4 version of the mod on Minecraft 1.20.1.
Please use the correct version on [curseforge](https://legacy.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/files/4587479) or [modrinth](https://modrinth.com/mod/shulkerboxtooltip/version/4.0.3+1.20-fabric).
