### ISSUE TITLE
 Critical injection failure

### ISSUE THREAD

**Issue by DinnerBeef** [MisterPeModder/ShulkerBoxTooltip#126]
#### Issue Description:

 Critical injection failure in lastest.log

#### What happens:

Game crashes when starting, only thing that appears is in the lastest.log

#### What you expected to happen:
Game not to crash

#### Steps to reproduce:

1. Install mod
2. Start game
3.  Game crashes
____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-forge-4.0.3+1.20.jar
- Minecraft: 1.20.1
- Froge Loader: 47.0.19

#### Your most recent log file where the issue was present: 
https://s.dinnerbeef.com/gOXe5/vixIdiri43.txt

**Comment by MisterPeModder** [comment]
It looks like this bug only occurs for the latest Forge versions,
While I work on a fix, you may downgrade Forge to version 47.0.3 (in PrismLauncher: instance > version > forge > change version > 47.0.3)

**Comment by MisterPeModder** [comment]
It fixed on the newest version [4.0.4+1.20.1-forge](https://modrinth.com/mod/shulkerboxtooltip/version/4.0.4+1.20.1-forge).
