### ISSUE TITLE
Game crashing with code exit 1

### ISSUE THREAD

**Issue by Kingxrs** [MisterPeModder/ShulkerBoxTooltip#127]
**Issue Description:**

The game tries to start and throws an error in general, checking the latest.log file showed the following error line

Mod ID: 'cloth_config', Requested by: 'shulkerboxtooltip', Expected range: '[10.0.0,)', Actual version: '[MISSING]'

I don't really know what you are referring to with the required version that you request when launching the game

**Affected Versions:** 

-shulkerboxtooltip-forge-4.0.3+1.20.jar and previous versions
-Minecraft: 1.20.1
-Forge Loader: 47.0.3
-OptiFine 1.20.1_HD_U_I5_pre6 

![Captura de pantalla (79)](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/81192409/71f6c2b5-b5ad-4011-8acc-8bee9bd02d15)

[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/11857379/latest.log)

**Comment by MisterPeModder** [comment]
This means you are missing the [Cloth Config mod](https://modrinth.com/mod/cloth-config/version/11.0.99+forge), jute make sure you have the correct version of the mod installed and it should work fine.
