### ISSUE TITLE
Suggestion: Vanilla improved tooltip

### ISSUE THREAD

**Issue by Scarlaid** [MisterPeModder/ShulkerBoxTooltip#128]
I had this in mind: "What if one improve Vanilla tooltip?"

So Vanilla tooltip for shulkers show 5 first items and then nothing else, which sucks because sometimes players could have to place down the shulker just to check what block 
My idea is that 
- The tooltip information line can be configured to show how many lines as the players like
- A hotkey to show all items in there, stackable

#### GIF to make this more detailed (based on [Tooltip+](https://github.com/itsmiir/tooltipsplus)):
![javaw_6risD9WI5F](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/90851437/5ba64020-3ea8-4af1-ac46-f1a91af79c9a)

**Comment by MisterPeModder** [comment]
Hi, thanks for the suggestion!
ShulkerBoxTooltip main feature is to present the items of containers *visually*, I do not see the value of adding more lines to the vanilla tooltip in addition to the mod's preview component.
Plus, that would just be copying Tooltip+ and unless I'm mistaken, based on your screenshot, it seems this mod does a pretty good job at improving the vanilla tooltips.

**Comment by Scarlaid** [comment]
The reason I gave this suggestion is Tooltip+ having incompatibility with packs that have custom icons
https://github.com/itsmiir/tooltipsplus/issues/24
Unlikely won't be fixed because it's what intended to work and the pack mentioned in that issue already said about incompatibility with mods that does the same

This mod is likely my only option to not install an extra library (like Fuzz/Selium ones, if I remember correctly)
A plus to somehow make it blend into the actual tooltip instead of being a separated container preview like MiniHUD (it does have a ShulkerPreview)

This is like almost a standalone of MiniHUD + Tooltip+, which will also solve the incompatibility issue, so as I thought, it would be an idea for other mods to have it too, might benefit in someway
It was worth suggesting, but yeah, this turns out just suggesting copying a mod 🦆

**Comment by Scarlaid** [comment]
Got a temporary workaround, I will close this, thanks
