### ISSUE TITLE
no descriptors for shulkerboxtooltip.json

### ISSUE THREAD

**Issue by Lost-Feight** [MisterPeModder/ShulkerBoxTooltip#13]
can there be a section in the readme, or a seperate file that describes the options for the shulkerboxtooltip.json file?

**Comment by MisterPeModder** [comment]
I added the list of configuration options in the [wiki](https://github.com/MisterPeModder/ShulkerBoxTooltip/wiki/Configuration-Options).
Thanks for the suggestion!
