### ISSUE TITLE
Mod is so good but i dont see a name of item

### ISSUE THREAD

**Issue by eeeeeeehuysi** [MisterPeModder/ShulkerBoxTooltip#130]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### Steps to reproduce:

1.Mod is so good but i dont see a name of item
2.Mod is so good but i dont see a name of item
3.Mod is so good but i dont see a name of item
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
I'm sorry but can you clarify what you mean? If you do not update your issue, I'll will close it.

**Comment by cajeiri** [comment]
@MisterPeModder I believe he wishes for a function where he can see the contents plus the item/stack names, sort of how the partial preview works in vanilla maybe?
