### ISSUE TITLE
No config on fabric

### ISSUE THREAD

**Issue by ack953** [MisterPeModder/ShulkerBoxTooltip#131]
On fabric, there is no in-game option or JSON file to edit the settings. I want to enable full view always.

**Comment by MisterPeModder** [comment]
Sorry for the late reply,
On Fabric, you'll have to install Mod Menu to get access to the configuration menu.
For both platforms, you click on Main Menu > Mods > ShulkerBoxTooltip > "open config" / gear icon

If you want to edit the JSON file manually, it is located under `.minecraft/config/shulkerboxtooltip.json5`.
