### ISSUE TITLE
Add compatibility with Carpet-AMS-Addition

### ISSUE THREAD

**Issue by sternschnaube** [MisterPeModder/ShulkerBoxTooltip#140]
https://github.com/Minecraft-AMS/Carpet-AMS-Addition/blob/master/README_en.md

The mod offers a rule to double the Shulker Box inventory size, but the tooltip shows still 27 stacks, not 54.

![javaw_tn8V04mRHG](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/120551916/e1e1b826-ac07-4199-acf3-18c1cd1aa9b4)

**Comment by MisterPeModder** [comment]
Yes, the size of a shulker box is hardcoded to 27.
I will into dynamically adjust inventory sizes.

**Comment by venaminecraft** [comment]
That's great, thanks 😊

**Comment by venaminecraft** [comment]
Thank you so much!!!
