### ISSUE TITLE
Support 1.20.4

### ISSUE THREAD

**Issue by Yanni-X** [MisterPeModder/ShulkerBoxTooltip#143]
... do i have to say anything else besides the title?

**Comment by ghost** [comment]
Please, @MisterPeModder

**Comment by dfox288** [comment]
I've upgraded the code to work with 1.20.4 and created a PR for it.

Could not test forge, because I only run fabric - but here are the files:

https://github.com/dfox288/ShulkerBoxTooltip/releases/tag/v4.0.8

**Comment by Crystal-Spider** [comment]
An official version would be nice to publish it in modpacks.

**Comment by MisterPeModder** [comment]
Done ! Sorry for the very long wait and thanks agains @dfox288 for your contribution !
