### ISSUE TITLE
Some dyes give wrong colors when crafted with leather armor

### ISSUE THREAD

**Issue by Mineralium** [MisterPeModder/ShulkerBoxTooltip#144]
#### Issue Description:
Black, orange, lime, green, and cyan dyes produce wrong color hex when applied to leather armor

#### What happens:
Black=262626, orange=F98026, lime=80C726, green=5E7C26, cyan=269C9C

#### What you expected to happen:
In vanilla or without this mod, black=1D1D21, orange=F9801D, lime=80C71F, green=5E7C16, cyan=169C9C

#### Steps to reproduce:
Dye any leather armor item with one of the dyes I listed using a crafting table

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 4.0.4
- Minecraft: 1.20.1
- Fabric Loader: 0.14.25
- Fabric API: 0.90.0
- Other mods (if relevant): none

#### Your most recent log file where the issue was present: 
[[pastebin link](https://pastebin.com/ewq2UxVS)]

**Comment by MisterPeModder** [comment]
Its fixed, the patch should be available in the next releases for MC 1.18.2, 1.19.4, and 1.20.4.
