### ISSUE TITLE
Ender chest won't preview

### ISSUE THREAD

**Issue by Riunea** [MisterPeModder/ShulkerBoxTooltip#146]
#### Issue Description:

Sometimes ender chest preview shows contents inside it and sometimes it just doesn't

#### What happens:
Sometimes when I hover to preview ender chest content, it just doesn't show

#### What you expected to happen:
Whenever I hover and preview it, it always need to show the content inside

#### Steps to reproduce:

1.Hover your mouse on ender chest
2.Press your preview button
3.Result
...

____
#### Affected Versions (Do *not* use "latest"):1.20.4

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Lightningtow** [comment]
It appears it previews your ender chest on local worlds but not servers, which makes sense because echest data is stored serverside. A workaround would be to have the mod cache your echest every time you open one, but that could result in outdated caches due to changing echest contents when the mod isnt installed, so some effort would be needed.

**Comment by MisterPeModder** [comment]
That's correct, I'm considering adding a fallback mode where the last known contents of the ender chest are shown along with a message along the lines of "displaying last known contents" of something.

**Comment by Lightningtow** [comment]
I recently discovered that [Chest Tracker](https://modrinth.com/mod/chest-tracker) integrates with ShulkerBoxTooltip to show the cached echest contents, may be worth exploring, for either the authors or anyone who comes across this thread later

**Comment by MisterPeModder** [comment]
I was unaware of Chest Tracker having compatibility for ShulkerBoxTooltip. It works quit well!
That "fixes" this issue I guess :)
