### ISSUE TITLE
Crash on launch when using quilt

### ISSUE THREAD

**Issue by HughSparks** [MisterPeModder/ShulkerBoxTooltip#154]
#### Issue Description:

When launching using quilt, game crashes.

#### What you expected to happen:

Launch of Minecraft without error.

#### Steps to reproduce:

1. Install latest version of Quilt
2. Install ShulkerBoxToolTip and Fabric API
3. Launch instance
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 4.1.0+
- Minecraft: 1.20.6
- Fabric Loader: NA
- Quilt Loader: 0.25.0
- Fabric API: 0.99.0
- Other mods (if relevant): Quilt

#### Your most recent log file where the issue was present: 

https://pastebin.com/nJHT0C7i

**Comment by MisterPeModder** [comment]
I just released a patch for this, it is available for download on [Modrinth](https://modrinth.com/mod/shulkerboxtooltip/version/4.1.0-alpha.2+1.20.6-fabric).
Thanks for reporting!
