### ISSUE TITLE
[1.20.1] Tooltip doesn't update correctly

### ISSUE THREAD

**Issue by MundM2007** [MisterPeModder/ShulkerBoxTooltip#155]
#### Issue Description:

I'm using KubeJS to modify the contents of the shulker box in the players inventory. I'm using `let slotItem = inventory.getItem(slotIndex)` and then modifying that item accordingly, modifying the contents of the items array. If the shulker Box is not held during this modification, it doesn't update the tooltip.

#### What happens:

Tooltip doesn't update

#### What you expected to happen:

That the tooltips update and show correctly

#### Steps to reproduce:

I'm using this kubejs code to modify the shulker:
```js
event.player.inventory.getItem(slotIndex)`
```
and switching between
```js
slotItem.nbt.BlockEntityTag.Items.addTag(i, {id: "minecraft:gold_ingot", Count:1, Slot:0})
```
and
```js
slotItem.nbt.BlockEntityTag.Items[i].Count = newCount
```
And wrapping that in the player chat event to trigger it. I've set an according slotIndex and index.
This is not modifying the display Tooltip

____
#### Affected Versions:

- ShulkerBoxTooltip: shulkerboxtooltip-forge-4.0.4+1.20.1.jar
- Minecraft: 1.20.1
- Forge loader: 47.2.32
- KubeJS: kubejs-forge-2001.6.5-build.7.jar
I don't think any other mods cause this.

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/15444779/latest.log)

**Comment by MundM2007** [comment]
Is there any method that needs to be called to correctly register an nbt change?

**Comment by MisterPeModder** [comment]
That's really weird, ShulkerBoxTooltip checks for NBT changes each frame so this is not supposed to happen.
I tested in "vanilla" using `/item replace` in a loop and the tooltip updates correctly regardless on what inventory or slot the shulker is in.
Can you share a minimum setup using KubeJS so that I can check on my end?

**Comment by MundM2007** [comment]
Ok, yeah sorry for reporting, it doesn't happen without the other mods. There seems to be a mod that directly interfers with this tick. Do you have an idea which it could be? 
this is a renamed mod list html, cause github doesn't allow html
[modlist.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/15445060/modlist.txt)

**Comment by MisterPeModder** [comment]
Sorry, I see no obvious mod in that list that may cause the problem. Have you tried disabling half the mods the isolate the culprit?

**Comment by MundM2007** [comment]
So I've found the culprit. It's Recipe Essentials: https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric this mod causes the gui to not update. Should I report this to them as I've noticed that this also affect custom model data?

**Comment by MundM2007** [comment]
newest version btw: recipeessentials-1.20.1-3.4.jar

**Comment by MundM2007** [comment]
Any Update on this?

**Comment by MundM2007** [comment]
@MisterPeModder

**Comment by MisterPeModder** [comment]
I missed your comments, sorry.
If the issue is not caused by ShulkerBoxTooltip, then you should report it over at the [Recipe Essentials issue tracker](https://github.com/someaddons/recipeessentials/issues).

**Comment by MundM2007** [comment]
ok thanks will do!
