### ISSUE TITLE
port to 1.21 version

### ISSUE THREAD

**Issue by dev-Younte** [MisterPeModder/ShulkerBoxTooltip#157]

**Comment by ThisCatLikesCrypto** [comment]
https://github.com/MisterPeModder/ShulkerBoxTooltip/pull/156#issuecomment-2173971917

if you're impatient

**Comment by dev-Younte** [comment]
> [#156 (comment)](https://github.com/MisterPeModder/ShulkerBoxTooltip/pull/156#issuecomment-2173971917)
> 
> if you're impatient

WOW!!! THANKS!!

**Comment by MisterPeModder** [comment]
Done. Sorry for the wait!
