### ISSUE TITLE
the fabric mod menu cannot change the settings of the shulkerbox tooltip

### ISSUE THREAD

**Issue by mrtilly** [MisterPeModder/ShulkerBoxTooltip#16]
#### Issue Description:
the fabric mod menu cannot change the settings of the shulkerbox tooltip

#### What happens:
when I open mod menu on fabric it didn't show the options for changing any thing of it

#### What you expected to happen:
when I open mod menu on fabric it would show the options for changing some settings of the Shulker box tooltip

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:v1.4.5+1.15
- Minecraft:1.15.2
- Fabric Loader:-0.8.2+build.194-1.15.2
- Fabric API:0.5.12+build.296-1.15.jar
- Other mods (if relevant):mod menu v1.10.2+build.

32

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
Try with the latest version of the mod (2.0.0+1.15.2)

**Comment by ScratchTTV** [comment]
I have the same problem and I use the newest version 2.0.1

**Comment by MisterPeModder** [comment]
@ScratchTTV I think you have the 'Show Key Hints' options tuned on, that is why you still have the `Shift: show contents` tooltip even with 'Tooltip Type' set to None.

@mrtilly All options are working on my side. What options are you trying to change? Are you on a server? Can you post the game log?

**Comment by ScratchTTV** [comment]
Yeah, but i only want to see the thing with shift and that but i set my Tooltip Type to none and it still dont work

**Comment by MisterPeModder** [comment]
What do you mean why "doesn't work"?

**Comment by ScratchTTV** [comment]
What i mean is that i set the Tooltip Type to none but it stays at Vanilla where you can see what it contains.
Easier to say is that i just want it to be like you have it but nothing happens when i edit Tooltip Type.

**Comment by MisterPeModder** [comment]
That's wierd... Are the other configuration options set to their default values?

**Comment by ScratchTTV** [comment]
Yep

**Comment by MisterPeModder** [comment]
The plot thickens...
Can you post a video or GIF of what your are doing?

**Comment by ScratchTTV** [comment]
I diden't do anything while I was joining.
And the video is in the zip file.
[2020-04-22 20-16-58.zip](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518208/2020-04-22.20-16-58.zip)

**Comment by MisterPeModder** [comment]
🤔 
Does this bug occur in singleplayer?

**Comment by ScratchTTV** [comment]
i dont know i can just test now... but ImpulseSv use it on Hermitcraft so i dont know, but i just test

**Comment by ScratchTTV** [comment]
I just tested in singleplayer, and it worked fine. I think the problem here is that i may not be suported for realms.... hope you fix :D
[2020-04-22 20-31-21.zip](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518286/2020-04-22.20-31-21.zip)

**Comment by MisterPeModder** [comment]
Try disabling the 'server intergration' option at the bottom of the menu and see if it works on your realm.

**Comment by ScratchTTV** [comment]
Still didn't work...
[2020-04-22 20-37-16.zip](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518320/2020-04-22.20-37-16.zip)

**Comment by MisterPeModder** [comment]
I just tried on a normal server, it works.
So this leaves us with only two possibilities:
1. Some other mod is **somehow** messing with the tooltip
2. This bug only occurs on realms, even though the tooltip is client-side only

**Comment by ScratchTTV** [comment]
This is the only mods i have on with Optifine
https://gyazo.com/073a94108b788e6e650e9994849d9eb1

**Comment by MisterPeModder** [comment]
I'll try with optifine on a server

**Comment by ScratchTTV** [comment]
Sure, but what can it do?
Its just adds some features that it

**Comment by MisterPeModder** [comment]
Still cannot reproduce the bug --'

**Comment by ScratchTTV** [comment]
... I really want it.
Do you have a realm to test it on?

**Comment by MisterPeModder** [comment]
Maybe a mixin silently failed, can the post the log ?
I don't have a realm, no

**Comment by ScratchTTV** [comment]
Here you go
[2020-04-22-7.log.gz](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518519/2020-04-22-7.log.gz)

**Comment by MisterPeModder** [comment]
Can you use [this](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518658/shulkerboxtooltip-2.0.1%2B1.15.2-SNAPSHOT.unzip.me.zip) version of the mod please?
It will provide extra debug information, that'll help me figure out what's wrong.
Once it is installed, please log into your realm and hover a shulker box. Then post the log here.

**Comment by ScratchTTV** [comment]
Here you go:
[2020-04-22-7.log.gz](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518706/2020-04-22-7.log.gz)

https://gyazo.com/29ddff7be29fb260db033b5fef873bbb

**Comment by MisterPeModder** [comment]
Thanks, but you posted the wrong logs, try posting `latest.log`

**Comment by ScratchTTV** [comment]
ok

**Comment by ScratchTTV** [comment]
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518723/latest.log)

**Comment by MisterPeModder** [comment]
Sorry to bother you again, but can you try with [this](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518890/shulkerboxtooltip-2.0.1%2B1.15.2-SNAPSHOT.2.zip) version instead ? Don't forget to remove the old debug version

**Comment by ScratchTTV** [comment]
Still dont work... il give you a picture and the logs so you can see it...
https://gyazo.com/8e7ff2fdc3b708102def14e113f5c120
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4518924/latest.log)

**Comment by MisterPeModder** [comment]
I found it, the realm you are on happens to have a datapack called `tryashtar's shulker-preview` installed, it changes the data of the shulker boxes in a way that confuses the mod

**Comment by ScratchTTV** [comment]
I have removed that but i can just try to see if it still are in the folders...

**Comment by MisterPeModder** [comment]
The datapack has harcoded the tooltip into the shulkers data so even if removed, the tooltip is still there

**Comment by MisterPeModder** [comment]
Try crafting a new shulker box to see if it works

**Comment by ScratchTTV** [comment]
okay

**Comment by ScratchTTV** [comment]
Yeah I found out that it aparently just have gone back into the folder after I removed it...

**Comment by ScratchTTV** [comment]
Har det her noget at gøre med modden?
https://gyazo.com/ca398fb7e90ad82ec1599549d5a328c6

**Comment by ScratchTTV** [comment]
sorry i wrote in Danish here it is in English: Does this have anything about the mod?

**Comment by MisterPeModder** [comment]
Try with the normal shulkerboxtooltip mod, it _should_ work this time

**Comment by ScratchTTV** [comment]
It worked.

Thank you very much, now I will enjoy using my shoulker boxes :D

**Comment by MisterPeModder** [comment]
No problem ^^
I will try to push a compatibility fix soon so datapacks don't mess with the tooltips.

**Comment by ScratchTTV** [comment]
Yea, its nothing about the mod, but do you know why I one shot dirt with my pickaxe on my realm and it also happens in singleplayer..

**Comment by MisterPeModder** [comment]
Are you on creative mode?

**Comment by ScratchTTV** [comment]
nope

**Comment by MisterPeModder** [comment]
Perhaps you have some kind of haste effect or maybe efficiency ?

**Comment by ScratchTTV** [comment]
Yea i have efficiency 5 and no haste, but efficiency 5 isen't that fast on dirt I have tried to much...

**Comment by MisterPeModder** [comment]
I don't know what could cause this then

**Comment by MisterPeModder** [comment]
The fix is now available at [curseforge](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/files/2937876).
