### ISSUE TITLE
Common Module isn't usable

### ISSUE THREAD

**Issue by Stein-N** [MisterPeModder/ShulkerBoxTooltip#165]
#### Issue Description:
The common artifact isn't usable outside of Arch Loom Multiloader setups.

Vanilla Gradle or ModDevGradle can't remap the Yarn Intermediary mappings, would it be possible to ship a version with the official Mojang Mappings?

#### What happens:
BlockEntityPreviewProvider.class
![image](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/128091790/6645e937-b037-4fa0-86c8-275126e00708)
![image](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/128091790/0d26883a-e94e-4a0a-987e-4dae08c9d57e)

#### What you expected to happen:
apply the cortrect Mappings

#### Steps to reproduce:

1. Use Vanilla Gradle or ModDevGradle in common
2. add common artifact of ShulkerBoxTooltip
3. get the wrong mappings 
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 5.0.2
- Minecraft: 1.21
- Fabric Loader: 15.11
- Fabric API: 0.100.4

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
Hello,
I added an artifact using official mappings (`-common-mojmap`).
Try replacing `"com.misterpemodder:shulkerboxtooltip-fabric:VERSION"` by `"com.misterpemodder:shulkerboxtooltip-fabric:VERSION"` in your build script and tell me if it vorks ok.

**Comment by Stein-N** [comment]
Works great thanks :)
