### ISSUE TITLE
1.18.2 Crash when using 3.4.4 , but 3.4.3 working fine

### ISSUE THREAD

**Issue by dirtTW** [MisterPeModder/ShulkerBoxTooltip#167]
#### Issue Description:

Crash when using 1.18.2 3.4.4 version

#### What happens:

3.4.4 version will crash at launch while using 3.4.3 just fine

#### What you expected to happen:

Normal launch without crashing

#### Steps to reproduce:

1. Instal ShulkerBoxTooltip 3.4.4 on Minecraft 1.18.2 
2. launch the game
3. Crash happen...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.4.4
- Minecraft: 1.18.2
- Fabric Loader: 0.15.11
- Fabric API: 0.77.0
- Other mods (if relevant): none

#### Your most recent log file where the issue was present: 

https://mclo.gs/VdJsHp4

**Comment by MisterPeModder** [comment]
Should be fixed in the 3.4.5 release.
