### ISSUE TITLE
Feature: ignore shoulder boxes that have specific nbt value.

### ISSUE THREAD

**Issue by mainrs** [MisterPeModder/ShulkerBoxTooltip#171]
I'm creating a data pack that uses shulker boxes to store structures. The shulkers are locked and cannot be opened by players.

This mod still shows their tooltips, which contains configuration item stacks, thus, no player relevant information.

It would be great if there is some kind of custom nbt tag I can add to these shulker boxes to make this mod ignore them and not show the tooltip for them.

Maybe `SBT:{Ignore:1b}`.

**Comment by MisterPeModder** [comment]
Done ! The feature will be available in the 4.2.0 and 5.1.0 releases for Minecraft 1.20.6 and 1.21.1 respectively. You may see how to use it in the [data-driven previews wiki page](https://github.com/MisterPeModder/ShulkerBoxTooltip/wiki/Data-Driven-Previews).
