### ISSUE TITLE
Game crashes when trying to access Config menu - No config file exists

### ISSUE THREAD

**Issue by zachbarber** [MisterPeModder/ShulkerBoxTooltip#173]
#### Issue Description:

When I click the "Config" button (Cloth Config API) the game crashes. There is also no config file in my config folder to edit directly.

#### What happens:

game crashes

no config file exists:
![image](https://github.com/user-attachments/assets/5397159f-9329-415d-addc-ca62eafbc928)

#### What you expected to happen:

Config for Shulker Box Tooltip would be opened without crashing.

#### Steps to reproduce:

1. Open "Mods" options in-game
2. Select "ShulkerBoxTooltip"
3. Select "Config"
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 5.0.4+1.21
- Minecraft: 1.21
- NeoForge 21.0.167

- Cloth Config v15 API: 15.0.130
- Dynamic FPS: 3.6.4
- EntityCulling: 1.7.0
- Model Gap Fix: 1.21-1.10
- ImmediatelyFast: 1.2.21+1.21.1
- Embeddium: 1.0.7+mc1.21
- Ferrite Core: 7.0.0
- Just Enough Items: 19.14.1.144

#### Your most recent log file where the issue was present: 

https://pastebin.com/VDJHPEWY

**Comment by MisterPeModder** [comment]
Fixed!
