### ISSUE TITLE
minecraft closes with this mod

### ISSUE THREAD

**Issue by Maxim666619** [MisterPeModder/ShulkerBoxTooltip#176]
English:
**Issue Description:**
The game crashes on startup with the ShulkerBoxTooltip mod installed. The crash occurs due to a failed injection of the `lockTooltipPosition` method into the `net.minecraft.client.gui.screens.inventory.AbstractContainerScreen` class.

**What Happens:**
The game closes with a critical error on startup.

**What You Expected:**
Expected the game to start without errors.

**Steps to Reproduce:**
1. Install Minecraft version 1.20.1 with Forge 47.3.0.
2. Install the ShulkerBoxTooltip mod version 4.0.3+1.20-forge.
3. Launch the game.

**Affected Versions (do not use "latest"):**
- ShulkerBoxTooltip: 4.0.3+1.20-forge
- Minecraft: 1.20.1
- Forge: 47.3.0

**Other Mods (if applicable):**
- Cloth Config API: 11.1.136
- MemoryLeakFix: 1.1.4
- JEI: 15.19.5.99

**Your Latest Log File Where the Issue Occurred:**
[Link to pastebin/gist/etc with your crash log]

Russian:
**Описание проблемы:**
Игра крашится при запуске с установленным модом ShulkerBoxTooltip. Краш происходит из-за неудачной инъекции метода `lockTooltipPosition` в класс `net.minecraft.client.gui.screens.inventory.AbstractContainerScreen`.

**Что происходит:**
Игра закрывается с критической ошибкой при запуске.

**Чего вы ожидали:**
Ожидалось, что игра запустится без ошибок.

**Шаги для воспроизведения:**
1. Установить Minecraft версии 1.20.1 с Forge 47.3.0.
2. Установить мод ShulkerBoxTooltip версии 4.0.3+1.20-forge.
3. Запустить игру.

**Затронутые версии (не используйте «последнюю»):**
- ShulkerBoxTooltip: 4.0.3+1.20-forge
- Minecraft: 1.20.1
- Forge: 47.3.0

**Другие моды (если применимо):**
- Cloth Config API: 11.1.136
- MemoryLeakFix: 1.1.4
- JEI: 15.19.5.99

**Ваш последний файл журнала, в котором возникла проблема:**
[Ссылка на pastebin/gist/etc с вашим журналом краша]#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
Try using the [4.0.4+1.20.1-forge version](https://modrinth.com/mod/shulkerboxtooltip/version/4.0.4+1.20.1-forge), it fixes exactly your issue.
It was caused by Forge 47.0.15 and later changing the way the Minecraft game code is patched for tooltips.
