### ISSUE TITLE
Colored Concrete does not appear in the preview, among some other things

### ISSUE THREAD

**Issue by Carbolemons** [MisterPeModder/ShulkerBoxTooltip#18]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
Can you provide more detail as to what is happening?
What version are on on?
Apart from concrete, what other items are not displaying?
Do you have other mods installed? If yes, please list them.

**Comment by Carbolemons** [comment]
My very bad, I do not remember writing this bug report, but it did ring a bell!

Fabric 0.8.2+build.194 / Minecraft 1.14.4

I went on and tried to re-create the problem, as it's not a clientside problem, but a server->client problem, as apparently the bug appears when servers are using the ViaVersion plugin to fool the client and server connection, although using an older version of minecraft for the server
The server in question I was having problems not _registering_ all the items in the box was on version 1.12.2, which is known to have not proper clientside connection

Maybe it _could_ be a menial fix, but the problem is super niche, and not something I would blame on you, as, it is very unexpected behaviour for a 1.14.4 client to connect to a 1.12.2 server!

I haven't tried using the clientside ViaVersion/ViaFabric/ViaBackwards mods to test if that fixes the shulkerbox problem, but I do know these mods fix the other completely unrelated problems!!

I'm sorry for this vague and random bug report, must've been really late for me lol
edit:
and at the time, I didn't believe that I probably wasn't connected to a non matching version (1.12.2) server, so I probably jumped and thought it was a random problem, as only some items seemed to not appear in the box
If my theory is correct, because the problem presented with _colored concrete_ and terracotta
I don't think the shulkerboxtooltip properly reads the 1.12.x (World Of Color) update, as I think 1.13 introduced new item id's for them? that could be my only reasoning to why the mod doesn't render unknown, custom, or outdated items
maybe a fix, if it works like this, would be to render the unknown texture with the raw item id name, instead of rendering nothing in the shortened preview?

But, if you do decide to tackle this random problem, it is recreatable entirely by connecting the latest fabric loader 1.14.4 client with shulkerboxtooltip to any pre 1.13 ViaVersion server
I could try and get more information if you really desire, but as this is a result entirely outside of the scope of what is reasonable, it may not be worth your time or effort to fix a rare problem presented by the fact that client and server versions do not match

i'm humbly sorry

**Comment by MisterPeModder** [comment]
ShulkerBoxTooltip uses the same method as vanilla to render items so I think the problem is that minecraft 1.14 doesn't know what to do with metadata and decides not to render the item.
It may also be a problem of ViaVersion not correctly translating 1.12 concrete/terracotta to their 1.13+ equivalent, but either way, this problem is way outside the scope of this mod as it would require patching the vanilla rendering methods.
Thank you for reporting this bug anyway.
