### ISSUE TITLE
Modrinth not marked as server side

### ISSUE THREAD

**Issue by RedTekk8** [MisterPeModder/ShulkerBoxTooltip#182]
#### Issue Description:

Im trying to use Modrinth mrpack files to assist with downloading and installing my minecraft server.  SBT is not marked as 'server required' on modrinth.  Because it is not marked for server side usage, the mrpack-install command is not working.  

Please mark the Modrinth listing as both Client-Side (client required) and Server-Side (server required)

#### What happens:
mrpack-install skips downloading SBT because it is marked as only client side.  

#### What you expected to happen:
The mod should automatically download on both client and server as the mod has a server component

#### Steps to reproduce:

Check the Modrinth listing under 'Compatibility'  
Currently the 'Supported Environments' is only listed as 'Client-side'
Should be marked as 'Server-side' as well

____
#### Affected Versions (Do *not* use "latest"):

All versions posted to Modrinth (Only checked 5, but I assume they are all marked the same)

**Comment by MisterPeModder** [comment]
Hi,
I marked server-side part as optional on Modrinth.
Thanks for reporting!

**Comment by 500-internal-server-error** [comment]
Hi, this issue appears to still not be resolved: it should show "client or server":

![Image](https://github.com/user-attachments/assets/598f3b90-cc16-407a-8ce7-9290849ee23c)

![Image](https://github.com/user-attachments/assets/62d90987-3fc9-4ca2-bda3-4809d52f93a6)

But it still only shows "client":

![Image](https://github.com/user-attachments/assets/7b425a68-efd2-47d9-8e04-b597bc699aa5)

![Image](https://github.com/user-attachments/assets/1250bdac-58df-4980-9efa-7d53436b56fa)
