### ISSUE TITLE
1.21.3 version labelled as 1.21.2 only on Modrinth

### ISSUE THREAD

**Issue by JulianVennen** [MisterPeModder/ShulkerBoxTooltip#183]
#### Issue Description:

Version [[Fabric 1.21.3] v5.2.0+1.21.3](https://modrinth.com/mod/shulkerboxtooltip/version/5.2.0+1.21.3-fabric)  is labelled as 1.21.2, not 1.21.3 on Modrinth.
The same issue exists for the NeoForge and Forge version

**Comment by MisterPeModder** [comment]
Good catch!
I fixed the versions on both Modrinth and CurseForge.
