### ISSUE TITLE
Fabric 1.21.3 Server Crash

### ISSUE THREAD

**Issue by Cardistymo** [MisterPeModder/ShulkerBoxTooltip#186]
#### What happens:

Server crashes when joining a server with ShulkerBoxTooltip installed on server and client.

#### What you expected to happen:

That the server doesn't crash and I can preview my enderchest via the mod.

#### Steps to reproduce:

1. Setup a fabric 1.21.3 server
2. add fabric-api-0.107.3+1.21.3
3. add shulkerboxtooltip-fabric-5.2.0+1.21.3
4. join with a fabric client (also shulkerboxtooltip-fabric-5.2.0+1.21.3 installed!)
____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 5.2.0
- Minecraft: 1.21.3
- Fabric Loader: 0.16.9
- Fabric API: 0.107.3
- Other mods (if relevant): no other server-side mods

#### Your most recent log file where the issue was present: 

[log file](https://mclo.gs/DmO7waj)

**Comment by MisterPeModder** [comment]
Fixed. A patch will be available for download soon.
