### ISSUE TITLE
Crash on pressing shift

### ISSUE THREAD

**Issue by VinceKezel** [MisterPeModder/ShulkerBoxTooltip#19]
#### Issue Description:
Game fully crashes

_I understand that using a minecraft snapshot newer than a mod risks a crash; It's no fault of the mod. However maybe this report can be helpful in adapting the next mod version._

#### What happens:
Game crashes when pressing shift while mousing over the shulker box in hotbar.

#### What you expected to happen:
Expected shulkerbox tooltip popup.

#### Steps to reproduce:
See image for the situation... pressing shift next causes the crash.

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: v2.0.2+20w17a
- Minecraft: 20w19a
- Fabric Loader: 0.8.2+build.194
- Fabric API: 0.10.1+build.336
- Other mods (if relevant):
      fabricmod_VoxelMap-1.9.17_for_1.16(20w18a)
      WI-Zoom-1.2-MC20w18a

#### Your most recent log file where the issue was present: 

[crash.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4602573/crash.txt)
[crash2.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4602579/crash2.txt)

![capture_shulkerbox_tooltip_precrash](https://user-images.githubusercontent.com/49579475/81463012-5706de80-9184-11ea-8177-1f60e74abb64.png)

**Comment by MisterPeModder** [comment]
I just released a patch for the latest snapshot, it *should* not crash anymore

**Comment by VinceKezel** [comment]
Works great!
