### ISSUE TITLE
https://github.com/MisterPeModder/ShulkerBoxTooltip/issues

### ISSUE THREAD

**Issue by MrEnrty** [MisterPeModder/ShulkerBoxTooltip#191]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by akoimeexx** [comment]
This has no information and no report of issues; should be closed.
