### ISSUE TITLE
Loading error with Java 12

### ISSUE THREAD

**Issue by Chocohead** [MisterPeModder/ShulkerBoxTooltip#2]
Using the Fabric launch modpack with 1.14, it loads fine with Oracle Java 8 but with OpenJ9's Java 12 there is an incompatible class change error: https://pastebin.com/691bdpAC

The versions of Cloth-Config and ModMenu appear to differ compared to what ShulkerBoxTooltip is compiled against, but the fact it seems happy on J8 but not J12 is very strange.

**Comment by MisterPeModder** [comment]
This is wierd, the log says cloth config `0.2.0+build.12` but ShulkerBoxTooltip includes the `0.2.1.14` version of this mod...

**Comment by MisterPeModder** [comment]
You are using the pre release 4 version of the mod, could you try with the lastest version to see if it is working, I changed how the mod menu compat is handled in [this commit](https://github.com/MisterPeModder/ShulkerBoxTooltip/commit/69b488ca20f99fe81aca120752b7662126c06455), so this might have already solved the issue

**Comment by sargunv** [comment]
Confirmed fixed in the latest version 1.1.2 (I'm on Java 11). The launch pack will need to update.
