### ISSUE TITLE
Crashing In single player after saving my world

### ISSUE THREAD

**Issue by ghost** [MisterPeModder/ShulkerBoxTooltip#21]
#### What happens: I go to exit my single player world and everytime minecraft crashes and gives me an error, never happens in mutiplayer, I also confirmed this also works on new worlds. (I'll include a screenshot of my mods)
https://user-images.githubusercontent.com/66574976/83981665-980a2400-a8e5-11ea-9ed6-510d1ab5a650.png

#### Steps to reproduce:
[crash-2020-06-07_17.17.42-client.txt] https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4743143/crash-2020-06-07_17.17.42-client.txt

1. Load up any single player world
2. Exit and Save
3. Crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 2.02
- Minecraft: 1.15.2
- Fabric Loader: 0.8.7 Build 201 
- Fabric API: 0.11.1 Build 312
- Other mods (if relevant): (Included Screenshot)

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
I have fixed this bug in the 1.16 branch, will backport the fix to 1.15 soon

**Comment by MisterPeModder** [comment]
The issue should be fixed now, the update will be available on curseforge shortly

**Comment by ghost** [comment]
Thank you, you mod is very useful, have a good day ^^
