### ISSUE TITLE
Crashes on the dedicated server

### ISSUE THREAD

**Issue by comp500** [MisterPeModder/ShulkerBoxTooltip#22]
#### Issue Description:

The mod causes the game to crash when run on a dedicated server.

#### What happens:
The game crashes, throwing a `java.lang.RuntimeException: Cannot load class net.minecraft.client.util.InputUtil$Key in environment type SERVER`.

#### What you expected to happen:
The mod to either be disabled, or to not do anything on a dedicated server.

#### Steps to reproduce:

1. Clone the repository at hash dd4b75a3 (Release 2.1.0 beta 2)
2. Run the Minecraft Server run configuration in IntelliJ

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 2.1.0-beta.1+1.16-pre2
- Minecraft: 1.16-pre2 and 1.16-rc1
- Fabric Loader: 0.8.7+build.201 and 0.8.8+build.202
- Fabric API: 0.11.7+build.356-1.16 and 0.12.5+build.367-1.16
- Other mods (if relevant): Auto Config 3.2.0-unstable in dev environment

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4808271/latest.log)

**Comment by MisterPeModder** [comment]
Should be fixed now!
