### ISSUE TITLE
Shulkerbox tooltip not liking modmenu

### ISSUE THREAD

**Issue by PSILONCRAFT** [MisterPeModder/ShulkerBoxTooltip#23]
#### Issue Description:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!

#### What happens:

Game crashes at startup

#### Steps to reproduce:

1. install latest fabric 1.16.1
2.add lots of mods
 I have the current mods installed
 fabric-api-0.14.0+build.371-1.16
immersive-portals-0.13(forMc1.16.1withFabric)
itemscroller-fabric-1.16.0-0.15.0-dev.20200624.214738 (1)
litematica-fabric-1.16.0-0.0.0-dev.20200627.000333
malilib-fabric-1.16.0-0.10.0-dev.21+beta.2
minihud-fabric-1.16.0-0.19.0-dev.20200625.014835
RoughlyEnoughItems-4.5.5
shuffle--1.15.2-1.1.2 (yeah it works)
shulkerboxtooltip-2.1.0+1.16.1 (1)
tweakeroo-fabric-1.16.0-0.10.0-dev.20200624.214908
worldedit-fabric-mc1.16.1-7.2.0-beta-01
3.
..

____
#### Affected Versions (Do *not* use "latest"):
fabric 1.16.1 0.8.8 + build.202.1.16.1
- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 

[crash-2020-06-28_00.50.22-client.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/4841376/crash-2020-06-28_00.50.22-client.txt)

**Comment by MisterPeModder** [comment]
You are running an older version of ModMenu made for the 20w22a snapshot, try using the latest version for 1.16.1
