### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [MisterPeModder/ShulkerBoxTooltip#24]
#### Issue Description:

(Near) Instant crash

#### What happens:

Crashes

#### What you expected to happen:

Load the main menu

#### Steps to reproduce:

1. make a fabric 1.16.1 installation
2. download the files from [this link](https://anonfiles.com/x9W5m8J4oa/mods_rar) and extract that into your mods folder
3. run said fabric install

**NOTE**: I did not install Xaero's Minimap by accident but the result was the same. Crash log was not necessarily the same (didn't check) but if it still crashes after a solution is present, I will make a new issue or continue this one

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:1.16.1
- Fabric Loader: 0.9.0+build.204-1.16.1
- fabric-api-0.16.2+build.385-1.16.1
- advancements-enlarger-0.2.2
- antighost-1.16-fabric0.13.1-1.1.2
- appleskin-mc1.16-fabric-1.0.11
- armor-visibility-1.0.1
- Autofish-0.8.6-fabric-mc1.16
- betterdroppeditems-1.2.1-1.16
- Blur-1.0.6-1.16.1.fabric
- cleancut-mc1.16-2.1-fabric
- clientcommands-2.4.3
- colormatic-2.2.2+mc.1.16.1
- Controlling-For-Fabric-1.1.2
- CustomSelectionBox-5.0.1
- dark-loading-screen-1.3.2
- durabilityviewer-20w17a-fabric0.6.2-1.7
- dynamic-fps-1.1.4
- FirstPersonMod-1.2.0
- GameInfo-mod-1.5.4+1.16
- HealthOverlay-1.16.1-3.6.12
- Hwyla-fabric-1.16.1-1.9.22-75
- itemscroller-fabric-1.16.1-0.15.0-dev.20200630.022843
- lambdynamiclights-fabric-1.2.2+1.16.1
- light-overlay-5.4.1
- litematica-fabric-1.16.1-0.0.0-dev.20200711.162756
- logical_zoom-0.0.4
- malilib-fabric-1.16.1-0.10.0-dev.21+arne.1
- meteor-client-0.2.8-1.16.1
- minihud-fabric-1.16.1-0.19.0-dev.20200701.005153
- modmenu-1.14.5+build.30
- phosphor-fabric-mc1.16.1-0.6.0+build.7
- PresenceFootsteps-r26+1.16-rc1
- ReAuth-1.16-Fabric-3.9.0
- replaymod-1.16.1-2.4.1
- RoughlyEnoughResources-2.0.2
- RoughlyEnoughItems-4.10.3
- ScreenshotToClipboardFabric-1.0.6
- shuffle-1.16.1-1.1.2
- shulkerboxtooltip-2.1.0+1.16.1
- slight-gui-modifications-1.2.0
- SmoothScrollingEverywhere-3.0.3-unstable
- sodium-fabric-mc1.16.1-0.1.0
- torohealth-1.16.1-fabric-1
- transparent-1.16.1-1.2.0
- tweakeroo-fabric-1.16.1-0.10.0-dev.20200630.023405
- window_title_changer-2.0.0-1.16.1
- XaerosWorldMap_1.8.1_Forge_1.16.1

#### Your most recent log file where the issue was present: 

[log](https://0bin.net/paste/fOXg1wwY4nkRDYSl#lqbAqfDg0WlzFT0vQgAI0JZ1Zqd8LL4GhfVa3HxDrMA)

**Comment by ghost** [comment]
Just realized, I may be using an incompatible version of minihud as described by [this](https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/23) issue, will reply once I have determined whether or not this is the problem

**Comment by ghost** [comment]
> Just realized, I may be using an incompatible version of minihud as described by [this](https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/23) issue, will reply once I have determined whether or not this is the problem

It appears to be the latest version, will remove minihud and go from there

**Comment by ghost** [comment]
[this](https://0bin.net/paste/Rz9fnFgagDdLxS26#S1epfaae4wdrCUTzRLKJW8Uxh0gvIit6k+qFjVgOM69) is the new crash report
Edit: So as to not confuse anyone, I removed the [INFO] lines

**Comment by MisterPeModder** [comment]
It appears the mod conflicts with meteor client...

**Comment by ghost** [comment]
hmm, ill remove it and see if that fixes, thanks for the quick response!

**Comment by MisterPeModder** [comment]
Meteor client has completely overridden a method in ShulkerBoxBlock that i use to detect when the tooltip is about to be displayed. I cannot do much to resolve this issue unless they change the way they patch the Minecraft methods in a non-destructive way...

**Comment by ghost** [comment]
ok, then I may see if it already includes a shulker tooltip? many clients do
