### ISSUE TITLE
Dark Mode feature request

### ISSUE THREAD

**Issue by Yrouel** [MisterPeModder/ShulkerBoxTooltip#26]
[shulker_box_tooltip_dark.png.zip](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/5147150/shulker_box_tooltip_dark.png.zip)

Dark version of the tooltip using the same color palette of the [Default Dark Mode](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode) resource pack (zipped version in case the image is compressed by github)

![shulker_box_tooltip_dark](https://user-images.githubusercontent.com/70481880/91664210-0548e200-eaee-11ea-9f2a-819c66bc0f93.png)

Would be nice to have an option to enable dark mode

**Comment by MisterPeModder** [comment]
The feature has been added, thank for the suggestion!
It will be available in the 1.16.3 release as a config option.
The mod can also use the dark mod setting from LibGui if installed.
