### ISSUE TITLE
The shulker is always open

### ISSUE THREAD

**Issue by afdezmor** [MisterPeModder/ShulkerBoxTooltip#27]
Hello 

I think that is a bug I have the shulker always open in the inv. 
![image](https://user-images.githubusercontent.com/46401084/92182041-fb571400-ee4a-11ea-9e79-dc5b9942430d.png)

These are the settings
![image](https://user-images.githubusercontent.com/46401084/92181996-dc588200-ee4a-11ea-804e-569e086ffaac.png)

And I don't press any key

**Comment by MisterPeModder** [comment]
I see that you have dark borders around the preview window, you might be using an older build of the mod, try using the latest version to see if that fixes it.
