### ISSUE TITLE
Server Settings reset after joining a server

### ISSUE THREAD

**Issue by liamdun** [MisterPeModder/ShulkerBoxTooltip#29]
#### Issue Description:

So today i was trying to turn the enderchest tooltip while playing on a server, it required a restart, so i restarted the game, and checked the con

#### What happens:
when going to the mod config through 'Mod Menu' and in the Server Category turning on client integration, those server settings will reset (after restarting) the moment you join a server

#### What you expected to happen:
the settings to save and for me to see the ender chest tooltip GUI

#### Steps to reproduce:

1. Open mod menu
2. Click on shulkerboxtooltip
3. Click on the the config button
4. Click on Server
5. Enable Client Integration and set Ender Chest Synchronization Type to Active
6. Press save and quit
7. it will ask for a restart, click Exit Minecraft
8. open the minecraft launcher and select the fabric installation than click play
(at this point if you open the server settings it'll say that Client Integration is enabled and Ender Chest Synchronization Type is set to Active)
9. join a server
10. hover over the ender chest and there will be no tooltip
(now if you open the server settings you'll see that Client Integration is disabled and Ender Chest Synchronization Type is set to None)
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: -2.1.0-beta.3+1.16-rc1 all the way up to 2.1.1+1.16.2 (havent tested 1.16.3)
- Minecraft: 1.16.2
- Fabric Loader: fabric-loader-0.9.1+build.205-1.16.2
- Fabric API: fabric-api-0.18.0+build.397-1.16
- Other mods (if relevant): none of my mods should effect anything to do with this issue

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/HQAk0SVs

**Comment by MisterPeModder** [comment]
Hmm.... That's an oversight!
The mod syncs the config between the client and the server by overwriting the previous values in the server category without saving the previous values beforehand.
Thankfully, this should be pretty easy to fix, as I only need to store a second instance of the config object.

**Comment by liamdun** [comment]
So is that something you're gonna fix in the next version or I can fix myself? if so how?

**Comment by MisterPeModder** [comment]
I will release a patch in a day maximum.

**Comment by liamdun** [comment]
thanks a lot dude, appreciate it
