### ISSUE TITLE
Preview by default

### ISSUE THREAD

**Issue by Madis0** [MisterPeModder/ShulkerBoxTooltip#3]
The mod does what it says, but what if I want to see the slots preview by default? 

There doesn't seem to be an option for that currently, only for swapping between "tooltip types" (aka preview _text_) and "modes" (shift vs alt+shift).

Using v1.1.2 on Fabric (1.14 release)

**Comment by MisterPeModder** [comment]
Good idea, I have not thought about that!

**Comment by MisterPeModder** [comment]
I added an 'alwaysOn' config option in the 1.2.0 version of the mod
