### ISSUE TITLE
doesnt work 

### ISSUE THREAD

**Issue by jarell321** [MisterPeModder/ShulkerBoxTooltip#32]
#### Issue Description:

i cant see what is in the shulkerbox

#### What happens:
i only see text

#### What you expected to happen:
to see what is in the shulkerbox

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip:
- Minecraft:
- Fabric Loader:
- Fabric API:
voxel map 

#### Your most recent log file where the issue was present: 
![2020-10-21_17 09 33](https://user-images.githubusercontent.com/73241861/96739681-570c3b00-13c0-11eb-84b4-f5fe21f1d5a6.png)

**Comment by MisterPeModder** [comment]
Are you using the latest version of the mod?

**Comment by amnotbananaama** [comment]
From the screenshot tooltip, it looks like you might be confusing this mod (which is a clientside mod for Fabric), with [ShulkerPreview](https://github.com/tryashtar/shulker-preview), which is a vanilla datapack made by someone else.
