### ISSUE TITLE
API Issue with custom items that have a lore similar to shulker boxes

### ISSUE THREAD

**Issue by OroArmor** [MisterPeModder/ShulkerBoxTooltip#36]
If a mod has an item similar to a shulker box that also has the lore of the items, there is no way to remove them and have continued compatibility with your mod.

I believe that line 58 in `ItemStackMixin` is where the issue is, as you are brute-forcing a check for it to be a vanilla shulkerbox.

Im not here to tell you how to fix this issue, but a tag or some form of registering system like with the view providers might work.

**Comment by MisterPeModder** [comment]
These checks were introduced in order to fix issues with shulker preview datapacks, I'll remove them as part of the 3.0 API changes.

**Comment by MisterPeModder** [comment]
Lore removal is now controlled by a configuration option (which is off by default).
I'm closing this issue.
