### ISSUE TITLE
"License" mispelled in fabric.mod.json, causing warning in log

### ISSUE THREAD

**Issue by saltyseadoggo** [MisterPeModder/ShulkerBoxTooltip#38]
This mod throws a warning in the game's output log upon the game starting up, which is as follows:
*The mod "shulkerboxtooltip" contains invalid entries in its mod json:*
*- Unsupported root entry "licence" at line 8 column 12*
This appears to be due to "license" being misspelled as "licence" in your fabric.mod.json. This should be a simple fix that will help keep the log clear.~

**Comment by MisterPeModder** [comment]
Oops! I fixed this in the 1.17 branch, but forgot to apply this to the 1.16 branch
