### ISSUE TITLE
Custom Item lore of shulker boxes gets removed/overriden by the mod.

### ISSUE THREAD

**Issue by Andre601** [MisterPeModder/ShulkerBoxTooltip#39]
#### Issue Description:

When adding custom lore to a shulkerbox (i.e. through command blocks or by using plugins on a modded server like Spigot) are those hidden and overriden by the mod with its own lore.

#### What happens:

Any lore of the shulkerbox is completely overriden by the mod instead of just overriding the lore depicting the content of the Shulkerbox itself.

#### What you expected to happen:

The mod's lore should be appended to the custom lore.

#### Steps to reproduce:

1. Get a shulkerbox
2. Add custom lore to it.
3. See mod overriding the lore

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 2.3.3+1.16.4
- Minecraft: 1.16.4
- Fabric Loader: 0.10.6+214
- Fabric API: 0.25.4+1.16.4
- Other mods (if relevant):

#### Your most recent log file where the issue was present: 
https://paste.gg/p/Andre601/e4544fc2bec34395b9151a036bc1a948 (Hope this is the right log)

#### Screenshots
Expected behaviour:
![2021-01-09_16 52 10](https://user-images.githubusercontent.com/11576465/104096155-10313180-529b-11eb-9eb8-8ff71b03aca7.png)

Actual behaviour:
![2021-01-09_16 53 59](https://user-images.githubusercontent.com/11576465/104096202-4ec6ec00-529b-11eb-98d7-9d66a98c5851.png)

**Comment by MisterPeModder** [comment]
This is a known issue that will get resolved in 1.17.
A workaround for now is to set the tooltip type to vanilla in the config menu/file.
