### ISSUE TITLE
shulkerboxtooltip crashes the instnace in multimc launcher

### ISSUE THREAD

**Issue by G93d14** [MisterPeModder/ShulkerBoxTooltip#4]
please find attached the error logs:

https://paste.ee/p/P0hR6

https://paste.ee/p/t869B

**Comment by G93d14** [comment]
https://paste.ee/p/zKZVh

**Comment by MisterPeModder** [comment]
Turns out I uploaded the from jar... It *should* work if you re-download the mod.

**Comment by MisterPeModder** [comment]
Thanks for reporting!
