### ISSUE TITLE
Lodestone compass that have it's respective lodestone removed would spin extremely quickly in the modded GUI

### ISSUE THREAD

**Issue by CalXee** [MisterPeModder/ShulkerBoxTooltip#44]
#### Issue Description:

If a lodestone compass doesn't have a lodestone where it's pointing to, instead of the needle spinning randomly, it spins extremely fast. This issue existed in vanilla in multiple instances of UI like this but this mod doesn't have this issue addressed.
#### What happens:
Instead of spinning normally, it spins really fast.

#### What you expected to happen:
It spins normally just like every other compass scenario.

____

#### Steps to reproduce:

1. Attach a compass to a lodestone
2. Put it into a shulker box
3. Break the lodestone
4. Look inside the shulker box using the modded UI

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: Every 1.16 version
- Minecraft: 1.16.x
- Fabric Loader: 0.11.2
- Fabric API: 0.29.4
- Other mods (if relevant): Not relevant

____

#### Video demonstrating the issue:

https://user-images.githubusercontent.com/68349758/111243172-faabf100-85d6-11eb-94c1-55f539d60d8c.mp4

**Comment by CalXee** [comment]
Here's a video demonstrating the issue.

https://user-images.githubusercontent.com/68349758/111243172-faabf100-85d6-11eb-94c1-55f539d60d8c.mp4

**Comment by MisterPeModder** [comment]
The issue seems to have fixed itself in the 1.17 branch, so I'll mark this issue as closed.
