### ISSUE TITLE
Shulker box tooltips don't appear at all

### ISSUE THREAD

**Issue by Balint817** [MisterPeModder/ShulkerBoxTooltip#46]
For some reason, my game just acts like the mod doesn't even exist, no matter what I do the shulker preview doesn't appear.
I wanted to switch to the dev version so that I could provide a more detailed log, but then the game just refuses to start and crashes.
Crash report and the latest log:
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/6204667/latest.log)

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/25/21 1:39 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'shulkerboxtooltip'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/item/Items
	at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltip.<clinit>(ShulkerBoxTooltip.java:50)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.EntrypointStorage$$Lambda$84/1537772520.get(Unknown Source)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.Items
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1299396616 bytes (1239 MB) / 1946157056 bytes (1856 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedchat: AdvancedChat 2.1.2
		advancednbttooltip: Advanced NBT Tooltips 1.4.0+build.3-1.16.5
		anvil_crushing_recipes: Anvil Crushing Recipes 1.0+MC1.16.2-1.16.5
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.10.138
		armorhotswap: ArmorHotswap 1.2
		autoconfig1u: Auto Config v1 Updated 3.3.1
		baritone: Baritone 1.6.3
		bedrock_breaking: Bedrock Breaking 1.0.2
		betterpingdisplay: Better Ping Display 1.1
		blue_endless_jankson: jankson 1.2.0
		cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
		chat_heads: Chat Heads 0.2.1+1.16.2
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.10.13
		cmdkeybind: Command Macros 1.5.2-1.16
		colormatic: Colormatic 2.2.8+mc.1.16.3
		com_github_kaptainwutax_biomeutils: BiomeUtils 590f697a2ccb6c6bdba8e2fea891a25ace75c947
		com_github_kaptainwutax_chunkrandomreversal: ChunkRandomReversal 209eefb8ed2bd097e3c55d3934ba508b664443da
		com_github_kaptainwutax_featureutils: FeatureUtils 25f73f26289a65a314cd66badc3c433d7f8c37b0
		com_github_kaptainwutax_latticg: LattiCG 38f0b3d33e15ad2e6ce9ddb1f588e2b9a8c96174
		com_github_kaptainwutax_mathutils: MathUtils 6c2d50eacad0241ff76119e6e703b70bac4b4bce
		com_github_kaptainwutax_seedutils: SeedUtils 8e310c079346fa55077fd1786b50dae0d2025336
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		commandblocksurvival: Command Block Survival 1.0.0
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		cotton: Cotton 1.1.0
		cotton-cauldron: Cotton Cauldron 1.1.0
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		craftable_god_apple: Craftable God Apple 1.0.0
		craftpresence: CraftPresence 1.7.6
		crawl: Crawl 0.8.2
		crowdin-translate: CrowdinTranslate 1.2
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		flytre_lib: FlytreLib 0.2.8
		food_highlight: FoodHighlight 1.0.1
		gatewayer: Gatewayer 1.0.0
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		horsestatsvanilla: Horse Stats Vanilla 4.1.6
		infinitemusic: Infinite Music 1.3.0
		infinityfix: Infinity Fix 1.1.0
		inventoryhud: Inventory HUD + 3.2.2
		inventorysorter: Inventory Sorter 1.7.7-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kubejs: KubeJS 1605.3.6-build.177
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libgui: LibGui 3.3.5+1.16.5
		lithium: Lithium 0.6.4
		mcwifipnp: Minecraft WLAN Plug-n-Play 1.2.8
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		misc_tab: MiscTab 1.0.0
		mm: Manningham Mills 2.1
		mobblindness: Mob Blindness 1.0.0
		modmenu: Mod Menu 1.16.7
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		paradoxconfig: Paradox Config 0.4.0-beta
		phosphor: Phosphor 0.7.1+build.11
		quickshulker: Quick Shulker 1.1.12-1.16
		recipeconditions: Fabric Recipe Conditions 0.3.0
		replaymod: Replay Mod 1.16.4-2.5.2
		rhino: Rhino 1.7.13-build.14
		riptide_fix: Riptide Fix 1.2.0
		roughlyenoughitems: Roughly Enough Items 5.10.181
		roughlyenoughitems-api: REI (API) 5.10.181
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.181
		roughlyenoughitems-runtime: REI (Runtime) 5.10.181
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		sectionsign: SectionSign 1.0.2
		seedcracker: Seed Cracker 0.2.3-beta
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		slotlock: SlotLock 1.0.1-BETA
		sodium: Sodium 0.1.0
		spruceui: SpruceUI 2.0.4+1.16
		stitchedsnow: Stiched Snow 1.0.1
		tellme: TellMe 0.9.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		transparent: Transparent 2.1.0
		verticalredstone: Vertical Redstone 1.2.0
		villagerhelper: Villager Helper 1.3.3
		vistas: Vistas 1.2.4
		voxelmap: VoxelMap 1.10.15
		whospetisthis: Who's Pet Is This 1.0.0
		winwonders: Window Wonders 0.1.2
		worldedit: WorldEdit 7.2.3+5680-135941e
		worldtime: WorldTime 1.16.5-fabric0.30.0-1.3.1
		wurst: Wurst Client v7.14-MC1.16.5
	Launched Version: fabric-loader-0.11.2-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\User\AppData\Roaming\.minecraft\crash-reports\crash-2021-03-25_13.39.00-client.txt

**Comment by haykam821** [comment]
I was able to fix this issue by deleting my configuration file entirely.

**Comment by MisterPeModder** [comment]
It was probably caused by the `enablePreview` setting in the mod's config that was set to false

**Comment by Balint817** [comment]
The preview is enabled. I'm not that braindead at least to disable that. Ticket remains open.

**Comment by MisterPeModder** [comment]
By chance, do you have the server integration option turned off ?

**Comment by Balint817** [comment]
Turning on server integration fixes it, but I don't think I **_should_** need server integration in singleplayer?

**Comment by MisterPeModder** [comment]
Right. Does this issue occur on the latest release of the mod ?

**Comment by Balint817** [comment]
I just updated to the newest version 1.16.5 that you posted a few days ago.
Considering that not much changed, this kinda surprised me, but on the newest version, this issue no longer occurs.

**Comment by MisterPeModder** [comment]
Yeah I fixed a bug where previews would not display when server integration was disabled in this release
