### ISSUE TITLE
How do i make it so it doesn't automatically stack the items

### ISSUE THREAD

**Issue by HudsonIs3pic** [MisterPeModder/ShulkerBoxTooltip#49]
i dont want the items to stack in total, for example: having 2 stacks of wool in a shulker would show as 128, but i want it to show as 2 seperate stacks, like it does when i open the shulker :)
it fixes this by pressing Alt, but is there a way to make that automatic

**Comment by Hi-ImKyle** [comment]
Set `Swap Modes` to yes in the config... or if you don't use Mod Menu, `true` in the config file.
