### ISSUE TITLE
Can't play on Hypixel with SBT 2.3.5, but SBT 2.3.4 works fine with no issues.

### ISSUE THREAD

**Issue by HEROshineMC** [MisterPeModder/ShulkerBoxTooltip#50]
#### Issue Description:

Whenever I try to play on Hypixel with the new 2.3.5 version of the mod, I get stuck in Limbo (commands to get out of Limbo do not work). This is not their anti-cheat, blacklisted client modifications detection, or anything intentional like that; it's definitely a glitch. I wasn't sure if I should report this to Hypixel or here, so I did both. This ONLY affects Hypixel, I haven't had any issues on other servers while using this mod. You may have to work with Hypixel support to fix this issue, or at least get a server log from them that shows the error it throws.

#### What happens:
Hypixel isn't compatible with the 2.3.5 version of Shulker Box Tooltip, so some sort of error causes Hypixel to reroute you to Limbo if you attempt to join any servers.

#### What you expected to happen:
Hypixel should be compatible with the 2.3.5 version of SBT, like it was with the 2.3.4 version of SBT.

#### Steps to reproduce:

1. Use the mod
2. Log onto Hypixel
3. You'll see the error in chat: "A disconnect occurred in your connection, so you have been routed to limbo!"
4. Typing `/lobby`, `/lobby bedwars`, `/play solo_insane`, or any other commands to get out of Limbo will attempt to load the server you're connecting to, but will immediately kick you back to Limbo.

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 2.3.5 (using 2.3.4 on Minecraft 1.16.4 works completely fine with this issue not being present)
- Minecraft: 1.16.5
- Fabric Loader: 0.11.3
- Fabric API: 0.34.2
- Other mods (if relevant): N/A

#### Your most recent log file where the issue was present: 

[I don't know if it'll be of any help, since it seems this issue is server-side, but here's my game log of me opening Minecraft with the same versions as from the section above, logging onto Hypixel, being stuck in Limbo, and trying `/lobby bedwars` before logging off.](https://pastebin.com/9aLnBmfG)

#### Note:
Apparently the 2.3.4 version of SBT works for 1.16.5! Hooray! I'll be using that for now until this issue is resolved :smile: Also I know that SBT doesn't do anything on Hypixel, since they don't have any shulker boxes or other NBT containers in inventories, but the reason this matters is because people don't want to take out SBT from their mods folder and reload Minecraft _every_ time they want to play Hypixel. Hope that explains it and hopefully I did a good job of explaining this issue.

Thanks, HERO :grin:

**Comment by MisterPeModder** [comment]
It seems this is caused by the switch to Fabric's new networking API, I'll investigate the issue, but in the meantime, you can disable server integration in the config menu or file.

**Comment by Disguys** [comment]
I also observed a similar problem with logging into the Mineplex server, apparently they also have similar protection.

**Comment by MisterPeModder** [comment]
It is finally fixed! you should be able to join Hypixel when the next patch (for both 1.16 and 1.17) releases soon
