### ISSUE TITLE
1.17 Version Crashes Server

### ISSUE THREAD

**Issue by AllOutJay** [MisterPeModder/ShulkerBoxTooltip#53]
#### Steps to reproduce:

1. Install Fabric for 1.17 on to the server.
2. Install Fabric API for 1.17 on to the server. 
3. Install ShulkerBoxTooltip for 1.17 on to the server.
4. Bootup server.

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-3.0.0-alpha.3+1.17
- Minecraft: 1.17
- Fabric Loader: 0.11.3
- Fabric API: fabric-api-0.35.0+1.17
- Other mods (if relevant): n/a

#### Your most recent log file where the issue was present: 

https://bin.bloom.host/feyafemomu.sql

**Comment by MisterPeModder** [comment]
The issue should be fixed with the latest alpha
