### ISSUE TITLE
Disabling the "Server Integration" option disables the whole mod

### ISSUE THREAD

**Issue by douira** [MisterPeModder/ShulkerBoxTooltip#55]
#### What happens:

When I disable the setting "Server Integration" the mod doesn't show any tooltips at all.

#### What you expected to happen:

I expected only server integration related features not to work.

#### Steps to reproduce:

1. Change "server integration" to No
2. Hover over shulker box in inventory
3. Observe that there is no tooltip or key hint

![Screenshot 2021-06-25 at 03 25 40](https://user-images.githubusercontent.com/17120022/123355005-0ce9e380-d565-11eb-8bf0-310d8e31c90d.png)
![Screenshot 2021-06-25 at 03 25 06](https://user-images.githubusercontent.com/17120022/123355008-0d827a00-d565-11eb-9d9f-3927997f291e.png)

(it works just fine when this setting is Yes)

____
#### Affected Versions (Do *not* use "latest"): 

- ShulkerBoxTooltip: shulkerboxtooltip-2.3.5+1.16.5
- Minecraft: 1.16.5
- Fabric Loader: fabric-loader-0.11.6-1.16.5
- Fabric API: fabric-api-0.36.0+1.16
- Other mods (if relevant): modmenu-1.16.9

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/douira/e7f3948ea0fbd9a2820fbe92871cf753)

**Comment by MisterPeModder** [comment]
I fixed the bug in the 1.17 branch, backporting to 1.16 soon

**Comment by douira** [comment]
Thanks!
