### ISSUE TITLE
Number of items above 1000 shortens to 1k

### ISSUE THREAD

**Issue by JohnyDL** [MisterPeModder/ShulkerBoxTooltip#57]
I'm having an issue where the number of items just rounds to 1k which is a PITA if I have 20 shulkers and I'm looking for the one with a single stack missing I can't use your mod anymore, can you make the rounding an optional toggle?

**Comment by MisterPeModder** [comment]
It is already present, it is named 'Abbreviate large item counts' in the preview category.
