### ISSUE TITLE
in some servers that has auction house, won't show the price of the shulkers

### ISSUE THREAD

**Issue by EGOIST1372** [MisterPeModder/ShulkerBoxTooltip#58]
#### Issue Description:

in some servers that has auction house, won't show the price and the seller of the shulker box

screnshots attached:
ss1: the info of shulker not showing
ss2: without the mod info showing
ss3-4-5: settings of the mod
ss6: my mod folder

#### What you expected to happen:

to show the info of the shulkers in /ah

#### Steps to reproduce:

1. join the Play.datblock.com server
2. join any server for instance survival
3. type /ah in chat and hit enter
4. hover on a shulker box to see the price of it
5. it won't show the price and seller (ss1)
6. now close the minecraft and remove the shulkerboxtooltip mod and try step 1-4 again
7. now it shows the info (ss2)

____
#### Affected Versions:

- ShulkerBoxTooltip: shulkerboxtooltip-2.3.6+1.16.5 (its been a problem from early versions of mod for 1.16.5 afaik)
- Minecraft: 1.16.5 fabric
- Fabric Loader: 0.11.3-1.16.5
- Fabric API: fabric-api-0.36.0+1.16
- Other mods : attached a ss for this one (ss6)

![ss1](https://user-images.githubusercontent.com/86555131/123542439-f5764a80-d75e-11eb-8fe8-8985fd45da42.png)
![ss2](https://user-images.githubusercontent.com/86555131/123542444-f8713b00-d75e-11eb-868b-5945dc0d7a6c.png)
![ss3](https://user-images.githubusercontent.com/86555131/123542446-f9a26800-d75e-11eb-8ebe-7c8278d822de.png)
![ss4](https://user-images.githubusercontent.com/86555131/123542448-fc04c200-d75e-11eb-8ab0-0d492b3b2dcb.png)
![ss5](https://user-images.githubusercontent.com/86555131/123542449-fdce8580-d75e-11eb-812e-a5962576a84a.png)
![ss6](https://user-images.githubusercontent.com/86555131/123542450-0030df80-d75f-11eb-8b3b-51cf5326877f.png)

**Comment by MisterPeModder** [comment]
I backported the hide shulker box lore option (which is set to `false` by default).
The custom tooltip should now display regardless of the tooltip type setting.
