### ISSUE TITLE
Feature request: old style tooltip

### ISSUE THREAD

**Issue by sschlester** [MisterPeModder/ShulkerBoxTooltip#59]
In the update to 1.17, the shulker tooltip is now inside of the main tooltip, similar to the bundle. However, it would be nice to have back the old style where the tooltip is outside, like in older versions.

![image](https://user-images.githubusercontent.com/86331870/123552002-34e26e00-d742-11eb-8532-0adfca3776e6.png)

**Comment by MisterPeModder** [comment]
Thanks for the suggestion, this feaature is already planned for the full 3.0.0 release.
