### ISSUE TITLE
Crash with 19w38b

### ISSUE THREAD

**Issue by Siphalor** [MisterPeModder/ShulkerBoxTooltip#6]
With the latest published jar the game crashes in production when trying to view a shulker box.
I rebuild the jar on my own for version 19w38b and that jar worked without problems in production.

Crash report: https://hastebin.com/axaxoxihot

**Comment by MisterPeModder** [comment]
That's is a issue caused by the shipped version of fabric-resource-loader being outdated, I will fix it soon.
