### ISSUE TITLE
REI and SBTT are conflicting, causing the game to crash.

### ISSUE THREAD

**Issue by sadboiweedpound** [MisterPeModder/ShulkerBoxTooltip#62]
#### Issue Description:

I just added this mod (SBTT) to my game since I found the mod's feature very useful. As I was attempting to search for a lantern in the REI search box, my game immediately crashed with the crash report saying that REI and SBTT are causing potential issues. After this happened, I restarted my game, loaded up my world, and tried searching for literally anything in the REI search box. As soon as I pressed ANY key in the search box, the game crashed.

#### What happens:

As soon as I begin typing in the search box for REI, the game crashes.

#### What you expected to happen:

I expected the game to stay running after trying to search for an item.

#### Steps to reproduce:

1. Load into a world (any world)
2. Open up the inventory
3. Begin typing in the REI search box

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.6
- Fabric API: 0.38.0
- Roughly Enough Items: v6.0.268-alpha

#### Your most recent log file where the issue was present: 

[https://pastebin.com/zXNz5ENn](https://pastebin.com/zXNz5ENn)

**Comment by sadboiweedpound** [comment]
Just wanted to let you know that there are other mods present in my game, but the crashlog specifically mentions REI and SBTT as the cause of the crash. If I have missed any information that may prove useful with resolving this issue, please let me know and I'll try to get back to you as soon as I can.

**Comment by MisterPeModder** [comment]
That's weird, I can't seem to reproduce your crash, even after installing all of your mods in their correct versions.
That being said, I think I know why the game crashed, it has to do with the tooltip key check being done in the wrong thread.

**Comment by R3alCl0ud** [comment]
I believe the crash is related to rendering of the tooltip for ender chests, I only started experiencing this crash on my modded server once I had put something into my ender chest.

**Comment by MisterPeModder** [comment]
The issue now *should* never happen again in the next release for Minecraft 1.17.1 & 1.18.2.
If the crash somehow occurs in the patch, please don't hesitate to reopen the issue.
