### ISSUE TITLE
Game enters infinite loading loop (see description for full details)

### ISSUE THREAD

**Issue by TheSweatyYeti** [MisterPeModder/ShulkerBoxTooltip#63]
#### Issue Description:

When you Save and Quit to Title from a save which has World Specific Resources, the resource pack loading screen which unloads the World Specific Resources enters an unrecoverable infinite loading loop that can only be ended by force closing the game. (Alt+F4, End Task, Kill Instance, etc.)
This only happens when Ender Chest Synchronisation Type is set to "Passive". If it's set to "None" or "Active", it doesn't happen, and it unloads the World Specific Resources as expected.

#### What happens:

Game enters infinite loading screen loop.

#### What you expected to happen:

Game successfully unloads World Specific Resources and returns to Title Screen with any other resource packs still active.

#### Steps to reproduce:

1. Open Game with Shulker Box Tooltip mod and Mod Menu active
2. Go to "Mods">"Shulker Box Tooltip">"Configure">"Server"
3. Set "Client Integration" to "Yes"; set "Ender Chest Synchronisation Type" to "Passive"
4. Return to title
5. Open a save which has "World Specific Resources" (A resource pack that is only active in that world. To get this, name a resource pack "resources.zip" and put in the world folder)
6. After the World Data has been read, chunk loading has reached 100%, and Terrain has been loaded, the Mojang Studios loading screen will appear in order to load the World Specific Resources. Then you will enter the world
7. After doing what ever you wish, press "Esc", and click "Save and Quit to Title"
8. After the world is saved, the Mojang Studios loading screen appears again in order to unload the World Specific Resources
9. Note how the loading screen gets stuck in an infinite loop where once the loading bar is finished, it starts again. This happens an untold number of times, forcing you to force quit the game. It also deactivates any other resource packs you have active
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: v3.0.1+1.17
- Minecraft: 1.17.1
- Fabric Loader: 0.11.6
- Fabric API: 0.40.0+1.17
- Mod Menu: 2.0.10
- OptiFabric: 1.11.20 (Relevance doubted)
- OptiFine: 1.17.1_HD_U_G9 (Relevance doubted)

#### Your most recent log file where the issue was present: 

https://paste.ee/p/C4CK2
(Note: At line "364 [14:24:51]" a vanilla bug happened where loading into Singleplayer world fails, and is taken to Multiplayer Server Selection screen instead. That is unrelated to this bug.)

**Comment by MisterPeModder** [comment]
Thanks for reporting! This should be fixed in the next release

**Comment by TheSweatyYeti** [comment]
Cool. Thanks
