### ISSUE TITLE
[1.16.5] Chest With Loot Table shows a ??????? on the tooltip if "Loot Table Info Type = Hide"

### ISSUE THREAD

**Issue by TBlazeWarriorT** [MisterPeModder/ShulkerBoxTooltip#65]
#### Issue Description:
???????
Chests pointing to a LootTable on their NBT show a "???????" at the end of their tooltip. This seems to be a bug and can't be disabled, but could be a feature if it was clearer in explaining wtf "???????" means.
Seems like despite "Loot Table Info Type" being set to Hide, it still tries to display something and just confuses the user. I'll start using Simple since it cannot be disabled anyways.

#### What happens:
???????
![image](https://user-images.githubusercontent.com/25572454/134827422-37144b08-f949-4dde-b0f8-c586ec0e2c54.png)

#### What you expected to happen:
I expected no "???????" but the game hit me with "???????" and I had to keep enabling/disabling mods to find who was causing "???????". ???????

#### Steps to reproduce:

1. do /give @p chest{BlockEntityTag:{LootTable:""}} 1
2. look at the chest
3. ???????

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-2.3.7+1.16.5.jar
- Minecraft: 1.16.5
- Fabric Loader: 0.11.6
- Fabric API: fabric-api-0.37.1+1.16.jar
- Other mods (if relevant): none relevant, only happens when I have ShulkerBoxTooltips on

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/7232446/latest.log)
[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
The `???????` appearing on tooltips when loot table info type is set to simple is not a bug as it mimicks vanilla behavior when hovering shulker boxes with loot tables.
However this is meant to only appear on shulker boxes, so I will fix that.

**Comment by MisterPeModder** [comment]
The fix will be available on the next release for Minecraft 1.17.1, keep in mind that I only support the current release (and some snapshots) of Minecraft unless it is a critical bug.
Thanks for reporting though!
