### ISSUE TITLE
Empty Keybinds causes GL error spam in logs and incompatibility with Multiconnect

### ISSUE THREAD

**Issue by Felix14-v2** [MisterPeModder/ShulkerBoxTooltip#66]
**Description**
First of all, you should disable tooltip activation keys (Shulker Box Tooltip settings → Controls → click on the keybind buttons and press "esc"). By itself, this causes spam with an GL error in logs when hovering on shulker boxes. If you have multiconnect installed, when you join to server for the second time, you can't also do it because of this error ([Demo](https://youtu.be/xW9r5Nfz8wc)):
![image]( https://user-images.githubusercontent.com/75726196/135732385-493a602a-5f87-48a7-95f6-75dbb4c26300.png )

Without multiconnect you can join again, but spam with GL errors in logs remain. 

**To reproduce**
1. Install Shulker Box Tooltip and Fabric API (* and MultiConnect optionally)
2. Disable SBT keybinds, open any GUI and hover to the shulker box
3. Open the latest.log file
4. See log spam
5.* Try to join to any server twice and see Java.lang.IllegalStateException error

...

____
#### Affected Versions:

- ShulkerBoxTooltip: 3.0.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.7
- Fabric API: 0.40.1
- Other mods: [MultiConnect](https://github.com/Earthcomputer/multiconnect) (1.4.15)

#### Logs: 
[2021-10-03-4.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/7272355/2021-10-03-4.log)
https://pastebin.com/hS1XAemG

**Comment by MisterPeModder** [comment]
This should be fixed in the next release, thanks for reporting!
