### ISSUE TITLE
Version 3.0.2 requiring much older version of cloth config

### ISSUE THREAD

**Issue by Venaf** [MisterPeModder/ShulkerBoxTooltip#68]
#### Issue Description:
Update seems to add requirement for older version of cloth config.  Reverting to previous version of shulkerbox tooltips resolves problem.  Can't find any versions of cloth config that are flagged 'clothconfig2' except for 1.16.5 releases.

#### What happens:
Game halts during load

#### What you expected to happen:
Normal loading to menu

#### Steps to reproduce:

1. Updated to newest release of Shulker Tooltips
2. Launched game
3. Popup very shortly after saying I'm missing Cloth-config2

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.2+1.17.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.7
- Fabric API: 0.41.0+1.17
- Other mods (if relevant): Cloth Config API: 5.0.38-fabric

#### Your most recent log file where the issue was present: 

https://pastebin.com/wm3CN4je

**Comment by MisterPeModder** [comment]
Thats wierd, there is no mention of 'clocth-config2' anywhere in the code.
I just tested and the game lanches fine.
Does your game explicitly tell that it is ShulkerBoxTooltip that is missing cloth-config2?

**Comment by Venaf** [comment]
It doesn't say that it's ShulkerBoxTooltip, but when I update to the most recent release via the curseforge loader, I get this:
![image](https://user-images.githubusercontent.com/2046512/138616642-935601c9-f030-45a8-8664-1853762579f0.png)

and downgrading to 3.0.1 lets it load just fine again.  It took me a long trial and error of figuring out it was shulkerboxtooltips (it's a fairly large set of mods with a lot of dependencies so the 50/50 method is a little difficult to do) but in the end it came down to just the different versions.  Of course, I'm sure there could be some weird conflict with other mods, the list from when I launch with the older version of ShulkerBoxTooltip is https://pastebin.com/iCZpuFA4

**Comment by MisterPeModder** [comment]
Fixed it. I included a version of cloth config made for 1.18 snapshots by mistake, a patched release should be available in ~5 minutes max.
