### ISSUE TITLE
Unable to join hypixel network with ShulkerBoxTooltip

### ISSUE THREAD

**Issue by glitchy-jpg** [MisterPeModder/ShulkerBoxTooltip#69]
#### Issue Description:
Unable to join hypixel

#### What happens:
Hypixel puts me in limbo when using shulkerboxtooltip

#### What you expected to happen:
To join a lobby instead of being put in limbo

#### Steps to reproduce:

1. Install ShulkerBoxToolTip
2. Join Hypixel
3. You're in Limbo now
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: v3.0.3
- Minecraft: 1.17.1
- Fabric Loader: 0.11.7 - 1.17.1
- Fabric API: 0.41.3 - 1.17.1
- Other mods (if relevant):
AFKTape 1.1.1 (Modified by me to work in 1.17.1)
BerdinskiysBear's ArmorHUD 0.3.4
Borderless Mining Reworked v2.0.0
FerriteCore 3.0.3
FPS-fabric 1.0
freelook 1.1.0 (NOTE - THIS ISN'T THE PROBLEM, I'VE TESTED IT ALREADY.) 
Inventory Control Tweaks 1.3.8 
Mod Menu 2.0.14
Modget 0.2.3
MultiConnect 1.4.15
Notes 1.0.8
OptiFabric 1.11.20 (OptiFine 1.17.1_HD_U_G9)
Replay Mod 2.6.1
Simple Rpc 2.5-fabric
Smooth Boot 1.6.0
cloth config API 5.0.38-fabric
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/7499014/latest.log)

**Comment by MisterPeModder** [comment]
This is a duplicate of issue #50, but is fixed not and you should be able to join Hypixel when the next patch releases (for both 1.16 and 1.17).
