### ISSUE TITLE
1.14.4 Game crash.

### ISSUE THREAD

**Issue by ToxicShourin** [MisterPeModder/ShulkerBoxTooltip#7]
game crashes at the launcher after installing with a message that a error occurred. [1.14.4] ShulkerBoxTooltip-1.3.1+1.14.4. No crash report is generated The crashes stop when i delete ShulkerBoxTooltip. Tried with only fabric / fabric api installed. Also tried with new version of fabric api still get crash w/o a report.

**Comment by MisterPeModder** [comment]
I can't reproduce the crash on my computer, can you post the exact versions of the mods you used?

**Comment by ToxicShourin** [comment]
Mods
Fabric loader 0.4.8+build. 159-1.14.4 "This is how it shows in launcher."
Fabric api 0.30 build 207 Also tried updating API to 0.4.0 build 240
ShulkerBoxTooltip-1.3.1+1.14.4.

I have completely removed all other mods to make sure they are not causing the game crash and they were

Voxelmap and optifine

**Comment by MisterPeModder** [comment]
Try updating loader to 0.6.2, this was probably the issue.
Also you don't need to add the fabric api yourself, all of the dependencies of shulkerboxtooltip are bundled with the mod.

**Comment by MisterPeModder** [comment]
any 0.6.X version of loader should work.

**Comment by ToxicShourin** [comment]
Testing that now actually.
Updating fabric works.

Any way you can add the required fabric version to the requirements list??

**Comment by MisterPeModder** [comment]
Added the required version to the mod description, thanks for the suggestion!
