### ISSUE TITLE
Incompatibility with TechReborn Energy Crystals [1.17.1]

### ISSUE THREAD

**Issue by itsdinkd** [MisterPeModder/ShulkerBoxTooltip#70]
Storing Energy Crystals from TechReborn (and maybe other crystals too) inside an Inmis backpack, crashes the game when you try to see the preview of the contents inside it (Tries to render the energy Crystal's stored energy).

SOLUTION: temporarily disable Shulker Box Tooltips and take the crystals out.

Crash Report: https://paste.corebot.dev/najatecoqa.php

Link to TR issue: https://github.com/TechReborn/TechReborn/issues/2599

**Comment by itsdinkd** [comment]
@MisterPeModder any chance of looking at this? its been 3 months.

**Comment by itsdinkd** [comment]
updates mod to 1.18.2

doesnt fix bugs

**Comment by MisterPeModder** [comment]
Updating to 1.18.2 was urgent because it prevented everyone from playing with the mod, this issue only occurs in a specific situation, so I do not deem it as important.

While yes, it has been 4 months since you filed this issue (I apologize for the delay), please keep in mind that I maintain this mod on my free time.

**Comment by itsdinkd** [comment]
I maintain my 2 modpacks during my free time (which is every day to every other day), a job that takes 60 hours a week, a discord server with 1k people, 3 mc servers, 2 kids and still find time to address and fix if i can even the smallest issues. Kinda urks me that you deprioritized this without even saying that as i would have removed your mod from my pack months ago. I only have given your mod 220k downloads no big deal I guess right

**Comment by MisterPeModder** [comment]
The crash is fixed at last! The patch will be available for mc 1.17.1 and 1.18.2 shortly.
