### ISSUE TITLE
Shulker Tooltip showing what's inside trinket instead of hovered.

### ISSUE THREAD

**Issue by fabbe50** [MisterPeModder/ShulkerBoxTooltip#75]
#### Issue Description:
The tooltip shows what's in the trinket equipped box instead of the one hovered over.

#### What happens:
It shows the trinket equipped shulker box's content instead of the one I'm hover over.

#### What you expected to happen:
Seeing what's inside the shulker box I'm hovering over.

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.5
- Minecraft: 1.18
- Fabric Loader: 0.12.12
- Fabric API: 0.46.1
- Other mods (if relevant): Trinket Shulker Boxes 2.0.1, Equipment Compare 1.2.11

![Screenshot_255](https://user-images.githubusercontent.com/8047187/152440721-95397434-fe13-40ef-aa7b-653c12d3d593.png)
![Sreenshot_254](https://user-images.githubusercontent.com/8047187/152440724-75f17062-b9e5-444f-881d-894549fd94fd.png)

**Comment by MisterPeModder** [comment]
Its fixed! It will be up in the next release for mc 1.18.2.
Note that Equipment Compare is not yet fully compatible with 1.18.2 at the moment, so the 'equipped' display will not show up.  


![2022-03-22_19 14 25](https://user-images.githubusercontent.com/7838479/159549166-bda14bf0-48b8-4948-b961-c49b5385bbd3.png)
