### ISSUE TITLE
How to make the name of things displayed in the shalker

### ISSUE THREAD

**Issue by DuckLuck1** [MisterPeModder/ShulkerBoxTooltip#77]
How to make the name of things appear as well as on the screenshot
![Inkedversion_1_LI](https://user-images.githubusercontent.com/97021371/162664081-599ad242-4e5d-447d-9590-aef90b3af73f.jpg)
t

**Comment by MisterPeModder** [comment]
Hello, this screenshot appears to use another mod or data pack.
But you can achieve a similar result in ShulkerBoxTooltip by changing the `Preview > Window Position` to `Outside (top)` and setting `Tooltip > Tooltip Type` to `Vanilla` in the configuration.

**Comment by DuckLuck1** [comment]
Thank you so much!!!
