### ISSUE TITLE
Won't display inside of Ender chest.

### ISSUE THREAD

**Issue by Psychodeus** [MisterPeModder/ShulkerBoxTooltip#80]
Sometimes it works, sometimes it don't display it. I don't know why.
![2022-05-11_14 07 58](https://user-images.githubusercontent.com/93028949/167780354-a0a7875c-2273-4331-8331-5dcf601de97a.png)

**Comment by MisterPeModder** [comment]
Hi, are you playing on single or multiplayer? Also does the preview work outside of the ender chest interface?

**Comment by PeerkeG** [comment]
I'm having the excact same issue. I play on single player.
I don't have shulker boxes yet, so I don't know if they will work :)

**Comment by MisterPeModder** [comment]
> I'm having the excact same issue. I play on single player. I don't have shulker boxes yet, so I don't know if they will work :)

You are playing on 1.18.2 right? Did you modify some config settings?

**Comment by PeerkeG** [comment]
> > I'm having the excact same issue. I play on single player. I don't have shulker boxes yet, so I don't know if they will work :)
> 
> You are playing on 1.18.2 right? Did you modify some config settings?

Yes, 1.18.2. And I didn’t modify anything. Didn’t even know that was possible..

**Comment by MisterPeModder** [comment]
Can any of you upload your game log where this issue happens? There should be some message related to ShulkerBoxTooltip's server handshake in it.

**Comment by Psychodeus** [comment]
> Hi, are you playing on single or multiplayer? Also does the preview work outside of the ender chest interface?

I'm playing on singleplayer, with 1.18.1 version.
Outside of ender chest? Haven't notice it yet, but so far it works well with shulker box.

**Comment by PeerkeG** [comment]
19:04:36.109
net.minecraft.server.MinecraftServer
Server thread
Preparing start region for dimension minecraft:overworld
19:04:36.718
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
19:04:36.741
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
19:04:37.157
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
19:04:37.674
net.minecraft.class_3951
Render thread
Preparing spawn area: 0%
19:04:38.166
net.minecraft.class_3951
Render thread
Preparing spawn area: 3%
19:04:38.658
net.minecraft.class_3951
Render thread
Preparing spawn area: 11%
19:04:39.159
net.minecraft.class_3951
Render thread
Preparing spawn area: 39%
19:04:39.667
net.minecraft.class_3951
Render thread
Preparing spawn area: 55%
19:04:40.297
net.minecraft.class_3951
Render thread
Time elapsed: 4141 ms
19:04:40.777
net.minecraft.class_1132
Server thread
Changing view distance to 16, from 10
19:04:40.781
net.minecraft.class_1132
Server thread
Changing simulation distance to 16, from 0
19:04:41.259
net.minecraft.class_3324
Server thread
PeerkeG24[local:E:6c93fc48] logged in with entity id 182 at (986.7376023919255, -29.0, -2115.145987904911)
19:04:41.286
net.minecraft.server.MinecraftServer
Server thread
PeerkeG24 joined the game
19:04:41.350
net.minecraft.class_2983
Render thread
[STDOUT]: Replacement `renderBlock` call:  method_3355.(Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1920;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLjava/util/Random;)Z
19:04:41.692
litematica
Render thread
Using 3 total BufferBuilder caches

19:04:42.105
net.minecraft.class_2512
Render thread
Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.105
net.minecraft.class_2512
Render thread
Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.105
net.minecraft.class_2512
Render thread
Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.105
net.minecraft.class_2512
Render thread
Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.106
net.minecraft.class_2512
Render thread
Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.106
net.minecraft.class_2512
Render thread
Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.106
net.minecraft.class_2512
Render thread
Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.106
net.minecraft.class_2512
Render thread
Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
19:04:42.145
ShulkerBoxTooltip
Render thread
[ShulkerBoxTooltip] Server integration enabled, attempting handshake...
19:04:42.147
ShulkerBoxTooltip
Netty Server IO #1
[ShulkerBoxTooltip] PeerkeG24: protocol version: 2.0
19:04:42.148
ShulkerBoxTooltip
Netty Local Client IO #0
[ShulkerBoxTooltip] Handshake succeeded
19:04:42.149
ShulkerBoxTooltip
Netty Local Client IO #0
[ShulkerBoxTooltip] Server protocol version: 2.0
19:04:42.150
ShulkerBoxTooltip
Server thread
[ShulkerBoxTooltip] Loading 1 plugin: shulkerboxtooltip
19:04:42.154
ShulkerBoxTooltip
Server thread
[ShulkerBoxTooltip] Registered 7 providers for mod shulkerboxtooltip
19:04:42.601
net.minecraft.class_163
Render thread
Loaded 783 advancements
19:05:07.935
net.minecraft.class_1132
Server thread
Saving and pausing game...
19:05:07.962
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:overworld
19:05:07.984
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_end
19:05:07.984
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_nether
19:05:11.436
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:11.726
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:16.692
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:16.707
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:30.967
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:31.008
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:51.445
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:05:58.569
net.minecraft.class_634
Render thread
Received passengers for unknown entity
19:06:06.175
net.minecraft.class_1132
Server thread
Saving and pausing game...
19:06:06.192
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:overworld
19:06:06.198
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_end
19:06:06.199
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_nether
19:06:28.289
net.minecraft.class_1132
Server thread
Saving and pausing game...
19:06:28.298
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:overworld
19:06:28.309
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_end
19:06:28.309
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[Herniland 3]'/minecraft:the_nether


At first it worked just fine, only when traveling through the nether, it stopped working..

**Comment by MisterPeModder** [comment]
fixed!
