### ISSUE TITLE
Suggestion: Ukrainian localization for mod [uk_ua.json]

### ISSUE THREAD

**Issue by Mark1ed** [MisterPeModder/ShulkerBoxTooltip#87]
I translated your mod into my language, so if you use my translation, don't worry about the quality of the translation, because I myself am Ukrainian :) [uk_ua.json [MediaFire]](https://www.mediafire.com/file/u1m1ntfklkodexo/uk_ua.json/file) I'm sorry if I didn't phrase it exactly how it should be, I'm just not very good at English...

**Comment by MisterPeModder** [comment]
Thanks a lot for your contribution! Your localization will be available in the next releases for 1.18.2 and 1.19
