### ISSUE TITLE
Just a log error..

### ISSUE THREAD

**Issue by PaladinFallen** [MisterPeModder/ShulkerBoxTooltip#89]
#### Issue Description:

Just an error on the log file

#### What happens:
Simple error when loading the log file

#### What you expected to happen:
I dunno...

#### Steps to reproduce:

1. Start game
2. Read log file

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: [[Fabric 1.19-1.19.1] v3.1.0+1.19]
- Minecraft: 1.191.1
- Fabric Loader: 0.14.8
- Fabric API: fabric-api-0.58.5+1.19.1
- Other mods (if relevant): None

#### Your most recent log file where the issue was present: 

[19:17:48] [ForkJoinPool-1-worker-4/WARN]: The mod "shulkerboxtooltip" contains invalid entries in its mod json:
- Unsupported root entry "old_mixins" at line 27 column 15
- Unsupported root entry "old_accessWidener" at line 61 column 22

**Comment by MisterPeModder** [comment]
That's just some old config I forgot to remove ^^. You can safely ignore this warning. I'll release a fix shortly.

**Comment by MisterPeModder** [comment]
The fix will be available in the next release very soon
