### ISSUE TITLE
Optional: Render all 27 fields instead of only the items that are in the container.

### ISSUE THREAD

**Issue by mainrs** [MisterPeModder/ShulkerBoxTooltip#9]
Would it be possible to add an option/config to render all fields allowing users to see in what slot what items are? Similar to [this](https://www.reddit.com/r/Minecraft/comments/ablqj3/dataresource_pack_that_shows_shulker_box_content/) datapack.

**Comment by MisterPeModder** [comment]
Pressing shift+control on the shulker box should show where all the items are, however there were a bug that prevented this, it got fixed on the latest version (for mc 1.15).
I will backport the fix the the 1.14.4 branch soon.
