### ISSUE TITLE
Not working with 1.19.2

### ISSUE THREAD

**Issue by ironik42** [MisterPeModder/ShulkerBoxTooltip#92]
#### Issue Description:
Current version does not work with 1.19.2

#### What happens:
Nothing

#### What you expected to happen:
Something related to be able to view contents of shulkers

#### Steps to reproduce:

1. copy mod to mod folder
2. load game
3. realize it doesn't work
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.1.1
- Minecraft: 1.19.2
- Fabric Loader: 0.11.0
- Fabric API: 0.60.0
- Other mods (if relevant): MaliLib 0.13.0

#### Your most recent log file where the issue was present: 
no logs to show

[pastebin/gist/etc link here]

**Comment by The-HAX0R-31337** [comment]
I'm having the same issue. I looked through my `latest.log` and didn't see anything referencing this mod.
