### ISSUE TITLE
config buttom missing 1.19.2

### ISSUE THREAD

**Issue by evilsga** [MisterPeModder/ShulkerBoxTooltip#98]
i know that some people commented on this but its been a while since this happened and it would be nice to have a solution for this bug

**Comment by MisterPeModder** [comment]
Hi, what versions of cloth-config and shulkerboxtooltip are you running?
You can see them by clicking the 'Show Libraries' button in mod menu.

**Comment by MisterPeModder** [comment]
Use the latest version of cloth-config for now, I will release a patch shortly to address this problem.
